version: '3.8'

services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    depends_on:
      - backend-dev
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DOCKER_ENV=true
      - VITE_API_URL=http://backend-dev:3001
    networks:
      - dev-network
    command: npm run dev -- --host 0.0.0.0

  backend-dev:
    build:
      context: ./fedai-backend-proxy
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ./fedai-backend-proxy:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3001
    env_file:
      - ./fedai-backend-proxy/.env
    networks:
      - dev-network
    command: npm run dev

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - dev-network
    volumes:
      - redis-data:/data

networks:
  dev-network:
    driver: bridge

volumes:
  redis-data:
