version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    volumes:
      - .:/app # Mount current directory for potential hot-reloading, though Vite build output might need specific handling.
    networks:
      - app-network

  backend:
    build:
      context: ./fedai-backend-proxy
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge