
import { LanguageCode, type Language, type AllUiStrings, type UiStrings, type PipelineUiStrings } from './types';
import { TRANSLATION_CACHE_PREFIX, TRANSLATION_CACHE_EXPIRY_MS, CACHE_THROTTLE_DELAY_MS } from './constants';
import { throttle } from 'lodash-es';


export const LANGUAGES: Language[] = [ // Ensure TR is first if it's default or primary
    { code: LanguageCode.TR, uiName: 'Türkçe', geminiPromptLanguage: 'Turkish' },
    { code: LanguageCode.EN, uiName: 'English', geminiPromptLanguage: 'English' },
    { code: LanguageCode.DE, uiName: 'Deutsch', geminiPromptLanguage: 'German' },
    { code: LanguageCode.ES, uiName: 'Español', geminiPromptLanguage: 'Spanish' },
    { code: LanguageCode.PT, uiName: 'Português', geminiPromptLanguage: 'Portuguese' },
    { code: LanguageCode.FR, uiName: 'Français', geminiPromptLanguage: 'French' },
];

const UI_STRINGS_PIPELINE_BASE_EN: Pick<UiStrings, 'pipelineStepImageUpload' | 'pipelineStepLocationData' | 'pipelineStepEnvironmentData' | 'pipelineStepAIAnalysis'> = {
  pipelineStepImageUpload: "Image Processing",
  pipelineStepLocationData: "Fetching Location",
  pipelineStepEnvironmentData: "Fetching Environment",
  pipelineStepAIAnalysis: "AI Analyzing",
};

const UI_STRINGS_PIPELINE_BASE_TR: Pick<UiStrings, 'pipelineStepImageUpload' | 'pipelineStepLocationData' | 'pipelineStepEnvironmentData' | 'pipelineStepAIAnalysis'> = {
  pipelineStepImageUpload: "Resim İşleniyor",
  pipelineStepLocationData: "Konum Alınıyor",
  pipelineStepEnvironmentData: "Çevre Verileri Alınıyor",
  pipelineStepAIAnalysis: "YZ Analiz Ediyor",
};

const UI_STRINGS_PIPELINE_BASE_DE: Pick<UiStrings, 'pipelineStepImageUpload' | 'pipelineStepLocationData' | 'pipelineStepEnvironmentData' | 'pipelineStepAIAnalysis'> = {
  pipelineStepImageUpload: "Bildverarbeitung",
  pipelineStepLocationData: "Standortabruf",
  pipelineStepEnvironmentData: "Umgebungsdatenabruf",
  pipelineStepAIAnalysis: "KI-Analyse",
};

const UI_STRINGS_PIPELINE_BASE_ES: Pick<UiStrings, 'pipelineStepImageUpload' | 'pipelineStepLocationData' | 'pipelineStepEnvironmentData' | 'pipelineStepAIAnalysis'> = {
  pipelineStepImageUpload: "Procesando Imagen",
  pipelineStepLocationData: "Obteniendo Ubicación",
  pipelineStepEnvironmentData: "Obteniendo Datos Ambientales",
  pipelineStepAIAnalysis: "Analizando IA",
};

const UI_STRINGS_PIPELINE_BASE_PT: Pick<UiStrings, 'pipelineStepImageUpload' | 'pipelineStepLocationData' | 'pipelineStepEnvironmentData' | 'pipelineStepAIAnalysis'> = {
  pipelineStepImageUpload: "Processando Imagem",
  pipelineStepLocationData: "Obtendo Localização",
  pipelineStepEnvironmentData: "Obtendo Dados Ambientais",
  pipelineStepAIAnalysis: "Analisando IA",
};

const UI_STRINGS_PIPELINE_BASE_FR: Pick<UiStrings, 'pipelineStepImageUpload' | 'pipelineStepLocationData' | 'pipelineStepEnvironmentData' | 'pipelineStepAIAnalysis'> = {
  pipelineStepImageUpload: "Traitement de l'Image",
  pipelineStepLocationData: "Obtention de la Localisation",
  pipelineStepEnvironmentData: "Obtention des Données Environnementales",
  pipelineStepAIAnalysis: "Analyse IA",
};


const PIPELINE_UI_STRINGS_INTERNAL: PipelineUiStrings = {
  [LanguageCode.EN]: UI_STRINGS_PIPELINE_BASE_EN,
  [LanguageCode.TR]: UI_STRINGS_PIPELINE_BASE_TR,
  [LanguageCode.DE]: UI_STRINGS_PIPELINE_BASE_DE,
  [LanguageCode.ES]: UI_STRINGS_PIPELINE_BASE_ES,
  [LanguageCode.PT]: UI_STRINGS_PIPELINE_BASE_PT,
  [LanguageCode.FR]: UI_STRINGS_PIPELINE_BASE_FR,
};


const UI_STRINGS_TR: UiStrings = {
  tagline: "Bitki sağlığı yolculuğunuzda akıllı yardımcınız.",
  allRightsReserved: "© " + new Date().getFullYear() + " Fedai. Tüm hakları saklıdır.",
  selectLanguage: "Dil Seçin",
  uploadImage: "Resim Yükle",
  captureImage: "Kamerayla Çek",
  clearImage: "Resmi Temizle",
  imagePreview: "Resim Önizleme",
  maxFileSizeError: (size) => `Maksimum dosya boyutu ${size}MB. Lütfen daha küçük bir resim seçin.`,
  fileTypeNotAllowedError: (types) => `İzin verilmeyen dosya türü. Lütfen şu türlerden birini seçin: ${types}.`,
  optionalDescriptionPlaceholder: "Bitkinin durumu hakkında ek bilgi (isteğe bağlı)...",
  analyzeButton: "Analiz Et",
  analyzingButton: "Analiz Ediliyor...",
  locationInfoTitle: "Konum Bilgisi",
  locationPermissionPromptMessage: "Doğru analiz ve yerel çözümler için konumunuza erişmemiz gerekiyor. Lütfen konum izni verin.",
  requestLocationPermissionButton: "Konum İznini Ver",
  locationPermissionDeniedMessage: "Konum izni reddedildi. Yaklaşık konum IP adresiniz üzerinden belirlenecek veya bazı yerel özellikler kullanılamayabilir.", 
  locationPermissionUnavailableMessage: "Konum servisleri kullanılamıyor. IP adresiniz üzerinden yaklaşık konum belirlenmeye çalışılacak.", 
  locationStatusFetching: "Konum bilgisi alınıyor...",
  locationStatusSuccessGps: (lat, lon) => `Konum: Enlem ${lat.toFixed(2)}, Boylam ${lon.toFixed(2)} (GPS).`, 
  locationStatusSuccessIp: (city, country, service) => `Yaklaşık konum: ${city}, ${country} (${service} üzerinden IP tabanlı).`, 
  locationStatusError: "Konum alınamadı. Lütfen daha sonra tekrar deneyin veya IP tabanlı konuma izin verin.", 
  locationGpsSuccessMessage: "Hassas konum aktif.",
  locationIpSuccessMessage: "Yaklaşık konum belirlendi.",
  locationErrorGeneral: "Konum belirlenemedi. İnternet bağlantınızı kontrol edin veya yerel ayarlarınızı gözden geçirin.",
  locationPermissionDeniedUserMessage: "Konum izni reddedildi. Doğru yerel analizler için konum bilgisi önerilir.",
  locationPermissionUnavailableUserMessage: "Konum servisleri kullanılamıyor. Doğru yerel analizler için konum bilgisi önerilir.",

  fetchingIpLocation: "IP adresinden konum bilgisi alınıyor...",
  ipLocationSuccess: "IP adresinden konum başarıyla alındı.", 
  ipLocationFailed: "IP adresinden konum alınamadı.", 
  weatherTabCurrent: "Anlık",
  weatherTabRecent: "Bu Ay",
  weatherTabHistorical: "5 Yıl Ort.",
  weatherFetching: "Hava durumu verileri alınıyor...",
  weatherUnavailable: "Hava durumu verileri alınamadı.",
  weatherLastUpdated: "Son Güncelleme",
  temperature: "Sıcaklık",
  humidity: "Nem",
  precipitation: "Yağış",
  windSpeed: "Rüzgar Hızı",
  weatherCondition: "Hava Koşulu",
  meanTemperature: "Ort. Sıcaklık",
  totalPrecipitation: "Toplam Yağış",
  fiveYearAverage: "5 Yıllık Ortalama",
  evapotranspirationLabel: "Evapotranspirasyon (ET₀)",
  evapotranspirationUnit: "mm/gün",
  gddLabel: "Büyüme Derece Gün (BDG)",
  gddUnit: "BDG",
  environmentalFactorsTitle: "Çevresel Faktörler",
  elevation: "Rakım",
  soilData: "Toprak Verileri",
  soilPH: "Toprak pH",
  soilOrganicCarbon: "Organik Karbon",
  soilCEC: "Katyon Değişim Kap. (KDK)",
  soilNitrogen: "Toplam Azot",
  soilTextureLabel: "Toprak Tekstürü",
  soilSandLabel: "Kum",
  soilSiltLabel: "Mil",
  soilClayLabel: "Kil",
  soilAWCLabel: "Kullanılabilir Su Kap. (KSK)",
  soilAWCUnit: "mm (0-5cm)",
  soilDataSourceNote: "Not: Toprak verileri SoilGrids model tahminleridir. Kesin değerler için yerel toprak analizi önerilir.",
  fetchingEnvironmentalData: "Çevresel veriler alınıyor...",
  environmentalDataUnavailable: "Çevresel veriler alınamadı.",
  environmentalDataLastUpdated: "Son Güncelleme",
  apiError: "API Hatası. Lütfen daha sonra tekrar deneyin.",
  apiKeyMissingError: "API anahtarı yapılandırılmamış. Analiz yapılamıyor.",
  analysisError: "Analiz sırasında bir hata oluştu. Lütfen tekrar deneyin. Sorun devam ederse servis durumlarını kontrol edin veya destek ile iletişime geçin.",
  noDiseaseFound: "Hastalık Bulunamadı veya Resim Yetersiz",
  diseaseNameLabel: "Hastalık Adı",
  definitionLabel: "Tanım",
  possibleCausesLabel: "Olası Nedenler",
  solutionsLabel: "Çözüm Önerileri",
  technicalAssessmentLabel: "Fedai Teknik Değerlendirmesi",
  similarPastCasesLabel: "Benzer Geçmiş Vakalar",
  solutionTypeCultural: "Kültürel",
  solutionTypeBiological: "Biyolojik",
  solutionTypeChemicalGeneral: "Kimyasal (Genel)",
  solutionTypeObservation: "Gözlem",
  solutionTypePreventive: "Önleyici",
  solutionTypeFertilizerAdjustment: "Gübre Ayarlaması",
  applicationNotesLabel: "Uygulama Notları",
  solutionExampleBrandsLabel: "Örnek Marka/Ürün Tipleri",
  solutionEstimatedBudgetLabel: "Tahmini Bütçe",
  consultLocalExperts: "Kimyasal mücadele için yerel tarım uzmanlarına danışın, yerel yönetmeliklere uyun ve sadece onaylı ürünleri etiket talimatlarına göre kullanın.",
  consultLocalExpertsSoil: "Gübreleme için kesin miktarlar ve uygun ürünler için mutlaka yerel toprak analizi yaptırın ve uzman tavsiyesi alın.",
  dataConsideredLocation: "Konum verileri dikkate alındı.",
  dataConsideredWeather: "Hava durumu verileri dikkate alındı.",
  dataConsideredEnvironmental: "Çevresel (rakım/toprak) veriler dikkate alındı.",
  followUpQuestionLabel: "Ek Soru",
  submitAnswerButton: "Cevabı Gönder",
  errorTitle: "Hata",
  wmoWeatherCodes: {
    0: 'Açık', 1: 'Parçalı Bulutlu', 2: 'Parçalı Bulutlu', 3: 'Çok Bulutlu',
    45: 'Sisli', 48: 'Kırağılı Sis',
    51: 'Hafif Çisenti', 53: 'Orta Çisenti', 55: 'Yoğun Çisenti',
    56: 'Hafif Donan Çisenti', 57: 'Yoğun Donan Çisenti',
    61: 'Hafif Yağmurlu', 63: 'Orta Yağmurlu', 65: 'Şiddetli Yağmurlu',
    66: 'Hafif Donan Yağmur', 67: 'Yoğun Donan Yağmur',
    71: 'Hafif Kar Yağışlı', 73: 'Orta Kar Yağışlı', 75: 'Yoğun Kar Yağışlı',
    77: 'Kar Taneleri',
    80: 'Hafif Sağanak Yağmur', 81: 'Orta Sağanak Yağmur', 82: 'Şiddetli Sağanak Yağmur',
    85: 'Hafif Kar Sağanağı', 86: 'Şiddetli Kar Sağanağı',
    95: 'Gök Gürültülü Fırtına', 96: 'Hafif Dolu ile Gök Gürültülü Fırtına', 99: 'Şiddetli Dolu ile Gök Gürültülü Fırtına'
  },
  serviceStatusTitle: "Servis Durumları",
  serviceStatusUp: "Aktif",
  serviceStatusDown: "Devre Dışı",
  serviceStatusError: "Hata",
  serviceStatusPending: "Kontrol Ediliyor...",
  serviceLocation: "Konum Servisi",
  serviceWeather: "Hava Durumu Servisi",
  serviceElevation: "Yükseklik Servisi",
  serviceSoil: "Toprak Veri Servisi",
  serviceAI: "Yapay Zeka Analiz Servisi",
  aiAnalysisInProgressMessage: "Yapay zeka analizi devam ediyor. Bu işlem, özellikle karmaşık görüntüler veya detaylı bağlamsal veriler için biraz zaman alabilir.",
  solutionEstimatedBudgetLow: "Düşük",
  solutionEstimatedBudgetMedium: "Orta",
  solutionEstimatedBudgetHigh: "Yüksek",
  solutionEstimatedBudgetUnknown: "Bilinmiyor",
  photoTipsTitle: "Fotoğraf İpuçları",
  photoTipsContent: "İyi bir analiz için:\n- Belirtilerin olduğu yaprak/bölgeyi net çekin.\n- İyi ışıklandırma sağlayın.\n- Mümkünse hem genel bitkiyi hem de yakın plan belirtiyi çekin.",
  showPhotoGuidelines: "Fotoğraf Yönergelerini Göster",
  hidePhotoGuidelines: "Fotoğraf Yönergelerini Gizle",
  photoGuidelineGoodLight: "İyi Işıklandırma: Parlak, dolaylı doğal ışık en iyisidir. Sert gölgelerden veya doğrudan güneş ışığından kaçının.",
  photoGuidelineClearFocus: "Net Odak: Belirtilerin net olduğundan emin olun. Bulanık fotoğraflar analizi zorlaştırır.",
  photoGuidelineAffectedPart: "Etkilenen Kısım: Öncelikle hastalıklı veya sorunlu görünen yaprağa, gövdeye veya meyveye odaklanın.",
  photoGuidelineWholePlantContext: "Genel Bitki Bağlamı: Mümkünse, bitkinin genel görünümünü gösteren bir fotoğraf da ekleyin.",
  photoGuidelineAvoidClutter: "Karmaşadan Kaçının: Arka planı basit tutun, böylece bitki öne çıkar.",
  photoGuidelineMultipleAngles: "Çoklu Açılar: Özellikle karmaşık sorunlar için farklı açılardan birkaç fotoğraf faydalı olabilir.",
  whyLocationImportantTitle: "Konum Neden Önemli?",
  whyLocationImportantContent: "Konumunuz, yerel hava durumu, yaygın hastalıklar ve bölgesel tarım uygulamaları hakkında bilgi sağlayarak daha doğru analiz ve çözümler sunmamıza yardımcı olur.",
  whyEnvironmentalDataImportantTitle: "Çevre Verileri Neden Önemli?",
  whyEnvironmentalDataImportantContent: "Rakım, toprak tipi gibi çevresel faktörler bitki sağlığını ve hastalık yatkınlığını etkiler. Bu veriler, analizin doğruluğunu artırır.",
  technicalAssessmentExplanationTitle: "Teknik Değerlendirme Nedir?",
  technicalAssessmentExplanationContent: "Bu bölümde Fedai, sağlanan görüntü ve bağlamsal verileri (hava durumu, toprak vb.) nasıl yorumladığını ve teşhise nasıl ulaştığını açıklar. Hangi faktörlerin önemli olduğu ve bunların olası hastalıkla nasıl ilişkili olduğu belirtilir.",
  noDiseaseGuidanceTitle: "Sonraki Adımlar",
  noDiseaseGuidanceInsufficientImage: "Görüntü kalitesi yetersiz olduğu için net bir teşhis yapılamadı.\n- Daha net, iyi ışıklandırılmış ve belirtilere odaklanmış bir fotoğraf yüklemeyi deneyin.\n- Bitkinizi gözlemlemeye devam edin, belirtilerde değişiklik olursa tekrar analiz edin.",
  noDiseaseGuidancePlantHealthy: "Bitkiniz sağlıklı görünüyor! Belirgin bir hastalık tespit edilemedi.\n- Bitkinizin bakımına devam edin.\n- Herhangi bir değişiklik fark ederseniz tekrar analiz edebilirsiniz.",
  noDiseaseGuidanceGeneralSymptoms: "Belirtiler genel veya çok erken olduğu için spesifik bir teşhis yapılamadı.\n- Bitkinizi birkaç gün daha gözlemleyin. Belirtiler belirginleşirse veya kötüleşirse yeni bir fotoğrafla tekrar analiz edin.\n- Endişeleriniz devam ederse yerel bir fidanlık veya tarım uzmanına danışın.",
  noDiseaseGuidanceObservationPrompt: "Gözlemlemeye devam edin. Belirtiler değişir veya kötüleşirse, yeni bir fotoğrafla tekrar analiz yapın veya bir uzmana danışın.",
  differentialDiagnosesLabel: "Ayırıcı Tanılar",
  imageQualityNotesLabel: "Görüntü Kalitesi Notları",
  qualitativeConfidenceLabel: "Teşhis Güvenilirliği",
  dataSourceDisclaimer: "Analiz, kamuya açık veri modellerine dayanmaktadır. Kesin sonuçlar için yerel testler altın standarttır.",
  errorNetwork: "Bağlantı kurulamadı. Lütfen internet bağlantınızı kontrol edin ve tekrar deneyin.",
  errorJsonParse: "Yapay zekanın yanıtı işlenirken bir sorun oluştu. Lütfen tekrar deneyin.",
  errorRateLimit: "Çok fazla istek gönderildi. Lütfen bir süre bekleyip tekrar deneyin.",
  errorAnalysisGeneric: "Analiz sırasında beklenmedik bir hata oluştu. Lütfen tekrar deneyin.",
  errorAnalysisTimeout: "Analiz beklenenden uzun sürdü. Lütfen ağ bağlantınızı kontrol edin veya daha sonra tekrar deneyin.",
  startDiagnosisButton: "Bitki Teşhisine Başla",
  thinkingTextAfterImageUpload: "Harika, fotoğrafınıza bakıyorum. Şimdi, daha doğru bir teşhis için yerel ortamı kontrol edelim...",
  viewMoreDetailsButton: "Daha Fazla Detay Göster",
  hideMoreDetailsButton: "Detayları Gizle",
  summaryTab: "Özet",
  solutionsTab: "Çözümler",
  technicalDetailsTab: "Teknik Detaylar",
  confidenceLevelLabel: "Güven Seviyesi",
  confidenceHigh: "Yüksek",
  confidenceMedium: "Orta",
  confidenceLow: "Düşük",
  confidenceUnknown: "Bilinmiyor",
  weatherSummaryTitle: "Hava Durumu Özeti",
  environmentalSummaryTitle: "Çevre Faktörleri Özeti",
  currentMonthTempTrend: "Bu Aylık Sıcaklık Eğilimi",

  backendDashboardTitle: "Arka Uç Servis Yönetimi",
  serviceProviderLabel: "Sağlayıcı(lar)",
  apiKeyManagementLabel: "API Anahtar Yönetimi",
  statusLabel: "Durum",
  aiServiceTitle: "YZ Analiz Servisi (Google Gemini)",
  geminiModelInfo: "Model: gemini-2.5-flash-preview-04-17",
  geminiKeyInfo: ".env dosyası üzerinden arka uç proxy tarafından güvenli bir şekilde yönetilir.",
  ipLocationServiceTitle: "IP Konum Servisi",
  ipLocationProvidersInfo: "Sağlayıcılar: ipapi.co (Birincil), ip-api.com (Yedek) - Proxy Üzerinden",
  ipLocationKeyInfo: "Genel API'ler kullanılır. Gelecekteki sağlayıcılar için anahtar gerekirse proxy üzerinden yönetilir.",
  weatherServiceTitle: "Hava Durumu Servisi",
  weatherProviderInfo: "Sağlayıcı: Open-Meteo - Proxy Üzerinden",
  weatherKeyInfo: "Genel API'ler kullanılır. Gelecekteki sağlayıcılar için anahtar gerekirse proxy üzerinden yönetilir.",
  elevationServiceTitle: "Yükseklik Servisi",
  elevationProvidersInfo: "Sağlayıcılar: Open-Elevation (Birincil), OpenTopoData (Yedek) - Proxy Üzerinden",
  elevationKeyInfo: "Genel API'ler kullanılır. Gelecekteki sağlayıcılar için anahtar gerekirse proxy üzerinden yönetilir.",
  soilServiceTitle: "Toprak Veri Servisi",
  soilProviderInfo: "Sağlayıcı: SoilGrids - Proxy Üzerinden",
  soilKeyInfo: "Genel API'ler kullanılır. Gelecekteki sağlayıcılar için anahtar gerekirse proxy üzerinden yönetilir.",
  howToUpdateConfigText: "Not: Servis sağlayıcılarını veya arka uç yapılandırmalarını değiştirmek için lütfen arka uç proxy'nin `server.js` dosyasını veya ortam değişkenlerini gerektiği gibi güncelleyin ve proxy sunucusunu yeniden başlatın. Bu panel bilgilendirme amaçlıdır.",
  switchToDiagnosisViewButton: "Teşhise Geri Dön",
  switchToDashboardViewButton: "Arka Uç Servisleri",
  leaveDiagnosisConfirmationTitle: "Teşhisten Ayrıl?",
  leaveDiagnosisConfirmationMessage: "Devam eden bir teşhisiniz var. Ayrılmak istediğinize emin misiniz? Mevcut resminiz ve verileriniz temizlenecek.",
  confirmButtonLabel: "Onayla",
  cancelButtonLabel: "İptal",
  
  // Newly added for centralization
  yourLocation: "Konumunuz",
  localEnvironmentInsightsTitle: "Yerel Ortam Bilgileri",
  typeYourAnswerPlaceholder: "Cevabınızı buraya yazın...",
  noSpecificSolutionsFoundTitle: "Spesifik Çözüm Bulunamadı",
  noSpecificSolutionsFoundMessage: "Bu teşhis için doğrudan bir çözüm önerisi bulunmuyor. Genel bitki bakımı ve gözlem yapmaya devam edin veya farklı bir resimle tekrar deneyin.",
  weatherDataUnavailableNoLocation: "Konum bilgisi olmadan hava durumu verileri alınamıyor.",
  currentWeatherInfoUnavailable: "Anlık hava durumu bilgisi alınamadı.",
  envDataUnavailableNoLocation: "Konum bilgisi olmadan çevre verileri alınamıyor.",
  ...PIPELINE_UI_STRINGS_INTERNAL[LanguageCode.TR],
};

const UI_STRINGS_EN: UiStrings = {
  tagline: "Your smart assistant for plant health.",
  allRightsReserved: "© " + new Date().getFullYear() + " Fedai. All rights reserved.",
  selectLanguage: "Select Language",
  uploadImage: "Upload Image",
  captureImage: "Capture with Camera",
  clearImage: "Clear Image",
  imagePreview: "Image Preview",
  maxFileSizeError: (size) => `Maximum file size is ${size}MB. Please select a smaller image.`,
  fileTypeNotAllowedError: (types) => `File type not allowed. Please select one of the following types: ${types}.`,
  optionalDescriptionPlaceholder: "Additional information about the plant's condition (optional)...",
  analyzeButton: "Analyze",
  analyzingButton: "Analyzing...",
  locationInfoTitle: "Location Information",
  locationPermissionPromptMessage: "We need access to your location for accurate analysis and local solutions. Please grant location permission.",
  requestLocationPermissionButton: "Grant Location Permission",
  locationPermissionDeniedMessage: "Location permission denied. Approximate location will be determined via IP, or some local features may be unavailable.", 
  locationPermissionUnavailableMessage: "Location services are unavailable. Attempting to determine approximate location via IP.", 
  locationStatusFetching: "Fetching location...",
  locationStatusSuccessGps: (lat, lon) => `Location: Lat ${lat.toFixed(2)}, Lon ${lon.toFixed(2)} (GPS).`, 
  locationStatusSuccessIp: (city, country, service) => `Approximate location: ${city}, ${country} (IP-based via ${service}).`, 
  locationStatusError: "Failed to get location. Please try again later or allow IP-based location.", 
  locationGpsSuccessMessage: "Precise location active.",
  locationIpSuccessMessage: "Approximate location determined.",
  locationErrorGeneral: "Could not determine location. Please check your internet connection or try again later.",
  locationPermissionDeniedUserMessage: "Location permission denied. Location information is recommended for accurate local analysis.",
  locationPermissionUnavailableUserMessage: "Location services unavailable. Location information is recommended for accurate local analysis.",
  fetchingIpLocation: "Fetching location from IP address...",
  ipLocationSuccess: "Successfully fetched location from IP address.", 
  ipLocationFailed: "Failed to fetch location from IP address.", 
  weatherTabCurrent: "Current",
  weatherTabRecent: "This Month",
  weatherTabHistorical: "5-Yr Avg",
  weatherFetching: "Fetching weather data...",
  weatherUnavailable: "Weather data unavailable.",
  weatherLastUpdated: "Last Updated",
  temperature: "Temperature",
  humidity: "Humidity",
  precipitation: "Precipitation",
  windSpeed: "Wind Speed",
  weatherCondition: "Weather Condition",
  meanTemperature: "Mean Temp.",
  totalPrecipitation: "Total Precip.",
  fiveYearAverage: "5-Year Average",
  evapotranspirationLabel: "Evapotranspiration (ET₀)",
  evapotranspirationUnit: "mm/day",
  gddLabel: "Growing Degree Days (GDD)",
  gddUnit: "GDD",
  environmentalFactorsTitle: "Environmental Factors",
  elevation: "Elevation",
  soilData: "Soil Data",
  soilPH: "Soil pH",
  soilOrganicCarbon: "Organic Carbon",
  soilCEC: "Cation Exchange Cap. (CEC)",
  soilNitrogen: "Total Nitrogen",
  soilTextureLabel: "Soil Texture",
  soilSandLabel: "Sand",
  soilSiltLabel: "Silt",
  soilClayLabel: "Clay",
  soilAWCLabel: "Available Water Cap. (AWC)",
  soilAWCUnit: "mm (0-5cm)",
  soilDataSourceNote: "Note: Soil data are SoilGrids model estimates. Local soil analysis is recommended for precise values.",
  fetchingEnvironmentalData: "Fetching environmental data...",
  environmentalDataUnavailable: "Environmental data unavailable.",
  environmentalDataLastUpdated: "Last Updated",
  apiError: "API Error. Please try again later.",
  apiKeyMissingError: "API key not configured. Cannot perform analysis.",
  analysisError: "An error occurred during analysis. Please try again. If the problem persists, check service statuses or contact support.",
  noDiseaseFound: "No Disease Found or Image Insufficient",
  diseaseNameLabel: "Disease Name",
  definitionLabel: "Definition",
  possibleCausesLabel: "Possible Causes",
  solutionsLabel: "Solutions",
  technicalAssessmentLabel: "Fedai Technical Assessment",
  similarPastCasesLabel: "Similar Past Cases",
  solutionTypeCultural: "Cultural",
  solutionTypeBiological: "Biological",
  solutionTypeChemicalGeneral: "Chemical (General)",
  solutionTypeObservation: "Observation",
  solutionTypePreventive: "Preventive",
  solutionTypeFertilizerAdjustment: "Fertilizer Adjustment",
  applicationNotesLabel: "Application Notes",
  solutionExampleBrandsLabel: "Example Brands/Product Types",
  solutionEstimatedBudgetLabel: "Estimated Budget",
  consultLocalExperts: "For chemical treatments, consult local agricultural experts, adhere to local regulations, and use only approved products according to label instructions.",
  consultLocalExpertsSoil: "For fertilization, always conduct local soil tests and seek expert advice for precise amounts and suitable products.",
  dataConsideredLocation: "Location data considered.",
  dataConsideredWeather: "Weather data considered.",
  dataConsideredEnvironmental: "Environmental (elevation/soil) data considered.",
  followUpQuestionLabel: "Follow-up Question",
  submitAnswerButton: "Submit Answer",
  errorTitle: "Error",
  wmoWeatherCodes: {
    0: 'Clear sky', 1: 'Mainly clear', 2: 'Partly cloudy', 3: 'Overcast',
    45: 'Fog', 48: 'Depositing rime fog',
    51: 'Light drizzle', 53: 'Moderate drizzle', 55: 'Dense drizzle',
    56: 'Light freezing drizzle', 57: 'Dense freezing drizzle',
    61: 'Slight rain', 63: 'Moderate rain', 65: 'Heavy rain',
    66: 'Light freezing rain', 67: 'Heavy freezing rain',
    71: 'Slight snow fall', 73: 'Moderate snow fall', 75: 'Heavy snow fall',
    77: 'Snow grains',
    80: 'Slight rain showers', 81: 'Moderate rain showers', 82: 'Violent rain showers',
    85: 'Slight snow showers', 86: 'Heavy snow showers',
    95: 'Thunderstorm', 96: 'Thunderstorm with slight hail', 99: 'Thunderstorm with heavy hail'
  },
  serviceStatusTitle: "Service Status",
  serviceStatusUp: "Up",
  serviceStatusDown: "Down",
  serviceStatusError: "Error",
  serviceStatusPending: "Pending...",
  serviceLocation: "Location Service",
  serviceWeather: "Weather Service",
  serviceElevation: "Elevation Service",
  serviceSoil: "Soil Data Service",
  serviceAI: "AI Analysis Service",
  aiAnalysisInProgressMessage: "AI analysis is in progress. This may take a few moments, especially for complex images or detailed contextual data.",
  solutionEstimatedBudgetLow: "Low",
  solutionEstimatedBudgetMedium: "Medium",
  solutionEstimatedBudgetHigh: "High",
  solutionEstimatedBudgetUnknown: "Unknown",
  photoTipsTitle: "Photo Tips",
  photoTipsContent: "For a good analysis:\n- Capture a clear image of the affected leaf/area.\n- Ensure good lighting.\n- If possible, take a photo of the whole plant and a close-up of the symptom.",
  showPhotoGuidelines: "Show Photo Guidelines",
  hidePhotoGuidelines: "Hide Photo Guidelines",
  photoGuidelineGoodLight: "Good Lighting: Bright, indirect natural light is best. Avoid harsh shadows or direct sunlight.",
  photoGuidelineClearFocus: "Clear Focus: Ensure symptoms are in sharp focus. Blurry photos hinder analysis.",
  photoGuidelineAffectedPart: "Affected Part: Focus primarily on the leaf, stem, or fruit that shows symptoms.",
  photoGuidelineWholePlantContext: "Whole Plant Context: If possible, also include a photo showing the overall plant.",
  photoGuidelineAvoidClutter: "Avoid Clutter: Keep the background simple so the plant stands out.",
  photoGuidelineMultipleAngles: "Multiple Angles: A few photos from different angles can be helpful, especially for complex issues.",
  whyLocationImportantTitle: "Why is Location Important?",
  whyLocationImportantContent: "Your location helps us provide more accurate analysis and solutions by considering local weather patterns, common diseases, and regional agricultural practices.",
  whyEnvironmentalDataImportantTitle: "Why is Environmental Data Important?",
  whyEnvironmentalDataImportantContent: "Environmental factors like elevation and soil type affect plant health and disease susceptibility. This data enhances the accuracy of the analysis.",
  technicalAssessmentExplanationTitle: "What is Technical Assessment?",
  technicalAssessmentExplanationContent: "In this section, Fedai explains how it interpreted the provided image and contextual data (weather, soil, etc.) to reach the diagnosis. It highlights which factors were significant and how they relate to the potential disease.",
  noDiseaseGuidanceTitle: "Next Steps",
  noDiseaseGuidanceInsufficientImage: "A clear diagnosis could not be made due to insufficient image quality.\n- Try uploading a clearer, well-lit photo focusing on the symptoms.\n- Continue to observe your plant and re-analyze if symptoms change.",
  noDiseaseGuidancePlantHealthy: "Your plant appears healthy! No significant disease was detected.\n- Continue with your plant care routine.\n- You can re-analyze if you notice any changes.",
  noDiseaseGuidanceGeneralSymptoms: "A specific diagnosis could not be made as symptoms are general or too early.\n- Observe your plant for a few more days. Re-analyze with a new photo if symptoms become more distinct or worsen.\n- If concerns persist, consult a local nursery or agricultural expert.",
  noDiseaseGuidanceObservationPrompt: "Continue to observe. If symptoms change or worsen, re-analyze with a new photo or consult an expert.",
  differentialDiagnosesLabel: "Differential Diagnoses",
  imageQualityNotesLabel: "Image Quality Notes",
  qualitativeConfidenceLabel: "Diagnostic Confidence",
  dataSourceDisclaimer: "Analysis is based on publicly available data models. Local tests are the gold standard for precision.",
  errorNetwork: "Could not connect. Please check your internet connection and try again.",
  errorJsonParse: "There was an issue processing the AI's response. Please try again.",
  errorRateLimit: "Too many requests. Please wait a moment and try again.",
  errorAnalysisGeneric: "An unexpected error occurred during analysis. Please try again.",
  errorAnalysisTimeout: "Analysis is taking longer than expected. Please check your network connection or try again later.",
  startDiagnosisButton: "Start Plant Diagnosis",
  thinkingTextAfterImageUpload: "Great, I'm looking at your photo. Now, let's check the local environment for a more accurate diagnosis...",
  viewMoreDetailsButton: "View More Details",
  hideMoreDetailsButton: "Hide Details",
  summaryTab: "Summary",
  solutionsTab: "Solutions",
  technicalDetailsTab: "Technical Details",
  confidenceLevelLabel: "Confidence Level",
  confidenceHigh: "High",
  confidenceMedium: "Moderate",
  confidenceLow: "Low",
  confidenceUnknown: "Unknown",
  weatherSummaryTitle: "Weather Summary",
  environmentalSummaryTitle: "Environmental Summary",
  currentMonthTempTrend: "This Month's Temp. Trend",

  backendDashboardTitle: "Backend Services Management",
  serviceProviderLabel: "Provider(s)",
  apiKeyManagementLabel: "API Key Management",
  statusLabel: "Status",
  aiServiceTitle: "AI Analysis Service (Google Gemini)",
  geminiModelInfo: "Model: gemini-2.5-flash-preview-04-17",
  geminiKeyInfo: "Handled securely by backend proxy via .env file.",
  ipLocationServiceTitle: "IP Location Service",
  ipLocationProvidersInfo: "Providers: ipapi.co (Primary), ip-api.com (Fallback) - via Proxy",
  ipLocationKeyInfo: "Uses public APIs. Key management via proxy if required by future providers.",
  weatherServiceTitle: "Weather Service",
  weatherProviderInfo: "Provider: Open-Meteo - via Proxy",
  weatherKeyInfo: "Uses public APIs. Key management via proxy if required by future providers.",
  elevationServiceTitle: "Elevation Service",
  elevationProvidersInfo: "Providers: Open-Elevation (Primary), OpenTopoData (Fallback) - via Proxy",
  elevationKeyInfo: "Uses public APIs. Key management via proxy if required by future providers.",
  soilServiceTitle: "Soil Data Service",
  soilProviderInfo: "Provider: SoilGrids - via Proxy",
  soilKeyInfo: "Uses public APIs. Key management via proxy if required by future providers.",
  howToUpdateConfigText: "Note: To change service providers or backend configurations, please update the backend-proxy's `server.js` file or environment variables as needed, and restart the proxy server. This dashboard is for informational purposes.",
  switchToDiagnosisViewButton: "Back to Diagnosis",
  switchToDashboardViewButton: "Backend Services",
  leaveDiagnosisConfirmationTitle: "Leave Diagnosis?",
  leaveDiagnosisConfirmationMessage: "You have a diagnosis in progress. Are you sure you want to leave? Your current image and data will be cleared.",
  confirmButtonLabel: "Confirm",
  cancelButtonLabel: "Cancel",

  // Newly added for centralization
  yourLocation: "Your Location",
  localEnvironmentInsightsTitle: "Local Environment Insights",
  typeYourAnswerPlaceholder: "Type your answer here...",
  noSpecificSolutionsFoundTitle: "No Specific Solutions Found",
  noSpecificSolutionsFoundMessage: "There are no direct solution recommendations for this diagnosis. Continue with general plant care and observation, or try again with a different image.",
  weatherDataUnavailableNoLocation: "Weather data cannot be fetched without location information.",
  currentWeatherInfoUnavailable: "Current weather information could not be retrieved.",
  envDataUnavailableNoLocation: "Environmental data cannot be fetched without location information.",
  ...PIPELINE_UI_STRINGS_INTERNAL[LanguageCode.EN],
};

const UI_STRINGS_DE_FULL: UiStrings = { 
  tagline: "Ihr intelligenter Assistent für Pflanzengesundheit.",
  allRightsReserved: "© " + new Date().getFullYear() + " Fedai. Alle Rechte vorbehalten.",
  selectLanguage: "Sprache wählen",
  uploadImage: "Bild hochladen",
  captureImage: "Mit Kamera aufnehmen",
  clearImage: "Bild löschen",
  imagePreview: "Bildvorschau",
  maxFileSizeError: (size) => `Maximale Dateigröße ist ${size}MB. Bitte wählen Sie ein kleineres Bild.`,
  fileTypeNotAllowedError: (types) => `Dateityp nicht erlaubt. Bitte wählen Sie einen der folgenden Typen: ${types}.`,
  optionalDescriptionPlaceholder: "Zusätzliche Informationen zum Zustand der Pflanze (optional)...",
  analyzeButton: "Analysieren",
  analyzingButton: "Analysiere...",
  locationInfoTitle: "Standortinformationen",
  locationPermissionPromptMessage: "Für eine genaue Analyse und lokale Lösungen benötigen wir Zugriff auf Ihren Standort. Bitte erteilen Sie die Standortgenehmigung.",
  requestLocationPermissionButton: "Standortgenehmigung erteilen",
  locationPermissionDeniedMessage: "Standortgenehmigung verweigert. Der ungefähre Standort wird über die IP-Adresse bestimmt, oder einige lokale Funktionen sind möglicherweise nicht verfügbar.",
  locationPermissionUnavailableMessage: "Standortdienste sind nicht verfügbar. Es wird versucht, den ungefähren Standort über die IP-Adresse zu bestimmen.",
  locationStatusFetching: "Standort wird abgerufen...",
  locationStatusSuccessGps: (lat, lon) => `Standort: Breitengrad ${lat.toFixed(2)}, Längengrad ${lon.toFixed(2)} (GPS).`,
  locationStatusSuccessIp: (city, country, service) => `Ungefährer Standort: ${city}, ${country} (IP-basiert über ${service}).`,
  locationStatusError: "Standort konnte nicht abgerufen werden. Bitte versuchen Sie es später erneut oder erlauben Sie IP-basierten Standort.",
  locationGpsSuccessMessage: "Präziser Standort aktiv.",
  locationIpSuccessMessage: "Ungefährer Standort bestimmt.",
  locationErrorGeneral: "Standort konnte nicht bestimmt werden. Bitte überprüfen Sie Ihre Internetverbindung oder versuchen Sie es später erneut.",
  locationPermissionDeniedUserMessage: "Standortgenehmigung verweigert. Standortinformationen werden für eine genaue lokale Analyse empfohlen.",
  locationPermissionUnavailableUserMessage: "Standortdienste nicht verfügbar. Standortinformationen werden für eine genaue lokale Analyse empfohlen.",
  fetchingIpLocation: "Standort wird von IP-Adresse abgerufen...",
  ipLocationSuccess: "Standort erfolgreich von IP-Adresse abgerufen.",
  ipLocationFailed: "Standort konnte nicht von IP-Adresse abgerufen werden.",
  weatherTabCurrent: "Aktuell",
  weatherTabRecent: "Dieser Monat",
  weatherTabHistorical: "5J.-Durchschn.",
  weatherFetching: "Wetterdaten werden abgerufen...",
  weatherUnavailable: "Wetterdaten nicht verfügbar.",
  weatherLastUpdated: "Letzte Aktualisierung",
  temperature: "Temperatur",
  humidity: "Luftfeuchtigkeit",
  precipitation: "Niederschlag",
  windSpeed: "Windgeschwindigkeit",
  weatherCondition: "Wetterbedingung",
  meanTemperature: "Mittlere Temp.",
  totalPrecipitation: "Gesamtniederschlag",
  fiveYearAverage: "5-Jahres-Durchschnitt",
  evapotranspirationLabel: "Evapotranspiration (ET₀)",
  evapotranspirationUnit: "mm/Tag",
  gddLabel: "Wachstumsgradtage (GDD)",
  gddUnit: "GDD",
  environmentalFactorsTitle: "Umweltfaktoren",
  elevation: "Höhe",
  soilData: "Bodendaten",
  soilPH: "Boden-pH",
  soilOrganicCarbon: "Organischer Kohlenstoff",
  soilCEC: "Kationenaustauschkap. (KAK)",
  soilNitrogen: "Gesamtstickstoff",
  soilTextureLabel: "Bodentextur",
  soilSandLabel: "Sand",
  soilSiltLabel: "Schluff",
  soilClayLabel: "Ton",
  soilAWCLabel: "Nutzbare Wasserkap. (nFK)",
  soilAWCUnit: "mm (0-5cm)",
  soilDataSourceNote: "Hinweis: Bodendaten sind SoilGrids-Modellschätzungen. Für genaue Werte wird eine lokale Bodenanalyse empfohlen.",
  fetchingEnvironmentalData: "Umweltdaten werden abgerufen...",
  environmentalDataUnavailable: "Umweltdaten nicht verfügbar.",
  environmentalDataLastUpdated: "Letzte Aktualisierung",
  apiError: "API-Fehler. Bitte versuchen Sie es später erneut.",
  apiKeyMissingError: "API-Schlüssel nicht konfiguriert. Analyse nicht möglich.",
  analysisError: "Bei der Analyse ist ein Fehler aufgetreten. Bitte versuchen Sie es erneut. Wenn das Problem weiterhin besteht, überprüfen Sie den Servicestatus oder wenden Sie sich an den Support.",
  noDiseaseFound: "Keine Krankheit gefunden oder Bild unzureichend",
  diseaseNameLabel: "Krankheitsname",
  definitionLabel: "Definition",
  possibleCausesLabel: "Mögliche Ursachen",
  solutionsLabel: "Lösungen",
  technicalAssessmentLabel: "Fedai Technische Bewertung",
  similarPastCasesLabel: "Ähnliche vergangene Fälle",
  solutionTypeCultural: "Kulturell",
  solutionTypeBiological: "Biologisch",
  solutionTypeChemicalGeneral: "Chemisch (Allgemein)",
  solutionTypeObservation: "Beobachtung",
  solutionTypePreventive: "Präventiv",
  solutionTypeFertilizerAdjustment: "Düngemittelanpassung",
  applicationNotesLabel: "Anwendungshinweise",
  solutionExampleBrandsLabel: "Beispielmarken/Produkttypen",
  solutionEstimatedBudgetLabel: "Geschätztes Budget",
  consultLocalExperts: "Für chemische Behandlungen konsultieren Sie lokale Agrarexperten, halten Sie sich an lokale Vorschriften und verwenden Sie nur zugelassene Produkte gemäß den Etikettanweisungen.",
  consultLocalExpertsSoil: "Für die Düngung führen Sie immer lokale Bodentests durch und holen Sie Expertenrat für genaue Mengen und geeignete Produkte ein.",
  dataConsideredLocation: "Standortdaten berücksichtigt.",
  dataConsideredWeather: "Wetterdaten berücksichtigt.",
  dataConsideredEnvironmental: "Umweltdaten (Höhe/Boden) berücksichtigt.",
  followUpQuestionLabel: "Folgefrage",
  submitAnswerButton: "Antwort senden",
  errorTitle: "Fehler",
  wmoWeatherCodes: { 
    0: 'Klarer Himmel', 1: 'Überwiegend klar', 2: 'Teilweise bewölkt', 3: 'Bedeckt',
    45: 'Nebel', 48: 'Reifnebel',
    51: 'Leichter Nieselregen', 53: 'Mäßiger Nieselregen', 55: 'Starker Nieselregen',
    56: 'Leichter gefrierender Nieselregen', 57: 'Starker gefrierender Nieselregen',
    61: 'Leichter Regen', 63: 'Mäßiger Regen', 65: 'Starker Regen',
    66: 'Leichter gefrierender Regen', 67: 'Starker gefrierender Regen',
    71: 'Leichter Schneefall', 73: 'Mäßiger Schneefall', 75: 'Starker Schneefall',
    77: 'Schneegriesel',
    80: 'Leichte Regenschauer', 81: 'Mäßige Regenschauer', 82: 'Starke Regenschauer',
    85: 'Leichte Schneeschauer', 86: 'Starke Schneeschauer',
    95: 'Gewitter', 96: 'Gewitter mit leichtem Hagel', 99: 'Gewitter mit starkem Hagel'
  },
  serviceStatusTitle: "Dienststatus",
  serviceStatusUp: "Verfügbar",
  serviceStatusDown: "Nicht verfügbar",
  serviceStatusError: "Fehler",
  serviceStatusPending: "Ausstehend...",
  serviceLocation: "Standortdienst",
  serviceWeather: "Wetterdienst",
  serviceElevation: "Höhendienst",
  serviceSoil: "Bodendatendienst",
  serviceAI: "KI-Analysedienst",
  aiAnalysisInProgressMessage: "Die KI-Analyse ist im Gange. Dieser Schritt kann einige Augenblicke dauern, insbesondere bei komplexen Bildern oder detaillierten Kontextdaten.",
  solutionEstimatedBudgetLow: "Niedrig",
  solutionEstimatedBudgetMedium: "Mittel",
  solutionEstimatedBudgetHigh: "Hoch",
  solutionEstimatedBudgetUnknown: "Unbekannt",
  photoTipsTitle: "Foto-Tipps",
  photoTipsContent: "Für eine gute Analyse:\n- Erfassen Sie ein klares Bild des betroffenen Blattes/Bereichs.\n- Sorgen Sie für gute Beleuchtung.\n- Machen Sie möglichst ein Foto der ganzen Pflanze und eine Nahaufnahme des Symptoms.",
  showPhotoGuidelines: "Foto-Richtlinien anzeigen",
  hidePhotoGuidelines: "Foto-Richtlinien ausblenden",
  photoGuidelineGoodLight: "Gute Beleuchtung: Helles, indirektes natürliches Licht ist am besten. Vermeiden Sie harte Schatten oder direkte Sonneneinstrahlung.",
  photoGuidelineClearFocus: "Klarer Fokus: Stellen Sie sicher, dass die Symptome scharf abgebildet sind. Unscharfe Fotos erschweren die Analyse.",
  photoGuidelineAffectedPart: "Betroffener Teil: Konzentrieren Sie sich hauptsächlich auf das Blatt, den Stängel oder die Frucht, die Symptome aufweist.",
  photoGuidelineWholePlantContext: "Gesamter Pflanzenkontext: Fügen Sie möglichst auch ein Foto bei, das die gesamte Pflanze zeigt.",
  photoGuidelineAvoidClutter: "Unordnung vermeiden: Halten Sie den Hintergrund einfach, damit die Pflanze hervorsticht.",
  photoGuidelineMultipleAngles: "Mehrere Winkel: Einige Fotos aus verschiedenen Winkeln können hilfreich sein, insbesondere bei komplexen Problemen.",
  whyLocationImportantTitle: "Warum ist der Standort wichtig?",
  whyLocationImportantContent: "Ihr Standort hilft uns, genauere Analysen und Lösungen zu liefern, indem lokale Wettermuster, häufige Krankheiten und regionale landwirtschaftliche Praktiken berücksichtigt werden.",
  whyEnvironmentalDataImportantTitle: "Warum sind Umweltdaten wichtig?",
  whyEnvironmentalDataImportantContent: "Umweltfaktoren wie Höhe und Bodentyp beeinflussen die Pflanzengesundheit und Krankheitsanfälligkeit. Diese Daten erhöhen die Genauigkeit der Analyse.",
  technicalAssessmentExplanationTitle: "Was ist eine technische Bewertung?",
  technicalAssessmentExplanationContent: "In diesem Abschnitt erklärt Fedai, wie es das bereitgestellte Bild und die Kontextdaten (Wetter, Boden usw.) interpretiert hat, um zur Diagnose zu gelangen. Es wird hervorgehoben, welche Faktoren signifikant waren und wie sie mit der potenziellen Krankheit zusammenhängen.",
  noDiseaseGuidanceTitle: "Nächste Schritte",
  noDiseaseGuidanceInsufficientImage: "Aufgrund unzureichender Bildqualität konnte keine eindeutige Diagnose gestellt werden.\n- Versuchen Sie, ein klareres, gut beleuchtetes Foto hochzuladen, das sich auf die Symptome konzentriert.\n- Beobachten Sie Ihre Pflanze weiter und analysieren Sie sie erneut, wenn sich die Symptome ändern.",
  noDiseaseGuidancePlantHealthy: "Ihre Pflanze scheint gesund zu sein! Es wurde keine signifikante Krankheit festgestellt.\n- Fahren Sie mit Ihrer Pflanzenpflegeroutine fort.\n- Sie können erneut analysieren, wenn Sie Änderungen feststellen.",
  noDiseaseGuidanceGeneralSymptoms: "Eine spezifische Diagnose konnte nicht gestellt werden, da die Symptome allgemein oder zu früh sind.\n- Beobachten Sie Ihre Pflanze noch einige Tage. Analysieren Sie erneut mit einem neuen Foto, wenn die Symptome deutlicher werden oder sich verschlimmern.\n- Wenn die Bedenken bestehen bleiben, wenden Sie sich an eine lokale Gärtnerei oder einen Agrarexperten.",
  noDiseaseGuidanceObservationPrompt: "Beobachten Sie weiter. Wenn sich die Symptome ändern oder verschlimmern, analysieren Sie erneut mit einem neuen Foto oder konsultieren Sie einen Experten.",
  differentialDiagnosesLabel: "Differentialdiagnosen",
  imageQualityNotesLabel: "Anmerkungen zur Bildqualität",
  qualitativeConfidenceLabel: "Diagnosesicherheit",
  dataSourceDisclaimer: "Die Analyse basiert auf öffentlich verfügbaren Datenmodellen. Lokale Tests sind der Goldstandard für Präzision.",
  errorNetwork: "Keine Verbindung möglich. Bitte überprüfen Sie Ihre Internetverbindung und versuchen Sie es erneut.",
  errorJsonParse: "Bei der Verarbeitung der KI-Antwort ist ein Problem aufgetreten. Bitte versuchen Sie es erneut.",
  errorRateLimit: "Zu viele Anfragen. Bitte warten Sie einen Moment und versuchen Sie es erneut.",
  errorAnalysisGeneric: "Während der Analyse ist ein unerwarteter Fehler aufgetreten. Bitte versuchen Sie es erneut.",
  errorAnalysisTimeout: "Die Analyse dauert länger als erwartet. Bitte überprüfen Sie Ihre Netzwerkverbindung oder versuchen Sie es später erneut.",
  startDiagnosisButton: "Pflanzendiagnose starten",
  thinkingTextAfterImageUpload: "Sehr gut, ich sehe mir Ihr Foto an. Lassen Sie uns nun die lokale Umgebung prüfen für eine genauere Diagnose...",
  viewMoreDetailsButton: "Mehr Details anzeigen",
  hideMoreDetailsButton: "Details ausblenden",
  summaryTab: "Zusammenfassung",
  solutionsTab: "Lösungen",
  technicalDetailsTab: "Technische Details",
  confidenceLevelLabel: "Konfidenzniveau",
  confidenceHigh: "Hoch",
  confidenceMedium: "Mittel",
  confidenceLow: "Niedrig",
  confidenceUnknown: "Unbekannt",
  weatherSummaryTitle: "Wetterübersicht",
  environmentalSummaryTitle: "Umweltübersicht",
  currentMonthTempTrend: "Temperaturtrend d. Monats",
  backendDashboardTitle: "Backend-Diensteverwaltung",
  serviceProviderLabel: "Anbieter",
  apiKeyManagementLabel: "API-Schlüsselverwaltung",
  statusLabel: "Status",
  aiServiceTitle: "KI-Analysedienst (Google Gemini)",
  geminiModelInfo: "Modell: gemini-2.5-flash-preview-04-17",
  geminiKeyInfo: "Sicher vom Backend-Proxy über .env-Datei gehandhabt.",
  ipLocationServiceTitle: "IP-Standortdienst",
  ipLocationProvidersInfo: "Anbieter: ipapi.co (Primär), ip-api.com (Fallback) - über Proxy",
  ipLocationKeyInfo: "Verwendet öffentliche APIs. Schlüsselverwaltung über Proxy, falls für zukünftige Anbieter erforderlich.",
  weatherServiceTitle: "Wetterdienst",
  weatherProviderInfo: "Anbieter: Open-Meteo - über Proxy",
  weatherKeyInfo: "Verwendet öffentliche APIs. Schlüsselverwaltung über Proxy, falls für zukünftige Anbieter erforderlich.",
  elevationServiceTitle: "Höhendienst",
  elevationProvidersInfo: "Anbieter: Open-Elevation (Primär), OpenTopoData (Fallback) - über Proxy",
  elevationKeyInfo: "Verwendet öffentliche APIs. Schlüsselverwaltung über Proxy, falls für zukünftige Anbieter erforderlich.",
  soilServiceTitle: "Bodendatendienst",
  soilProviderInfo: "Anbieter: SoilGrids - über Proxy",
  soilKeyInfo: "Verwendet öffentliche APIs. Schlüsselverwaltung über Proxy, falls für zukünftige Anbieter erforderlich.",
  howToUpdateConfigText: "Hinweis: Um Dienstanbieter oder Backend-Konfigurationen zu ändern, aktualisieren Sie bitte die `server.js`-Datei des Backend-Proxys oder die Umgebungsvariablen und starten Sie den Proxy-Server neu. Dieses Dashboard dient zu Informationszwecken.",
  switchToDiagnosisViewButton: "Zurück zur Diagnose",
  switchToDashboardViewButton: "Backend-Dienste",
  leaveDiagnosisConfirmationTitle: "Diagnose verlassen?",
  leaveDiagnosisConfirmationMessage: "Sie haben eine laufende Diagnose. Sind Sie sicher, dass Sie sie verlassen möchten? Ihr aktuelles Bild und Ihre Daten werden gelöscht.",
  confirmButtonLabel: "Bestätigen",
  cancelButtonLabel: "Abbrechen",

  // Newly added for centralization
  yourLocation: "Ihr Standort",
  localEnvironmentInsightsTitle: "Einblicke in die lokale Umgebung",
  typeYourAnswerPlaceholder: "Geben Sie hier Ihre Antwort ein...",
  noSpecificSolutionsFoundTitle: "Keine spezifischen Lösungen gefunden",
  noSpecificSolutionsFoundMessage: "Für diese Diagnose gibt es keine direkten Lösungsempfehlungen. Fahren Sie mit der allgemeinen Pflanzenpflege und Beobachtung fort oder versuchen Sie es mit einem anderen Bild erneut.",
  weatherDataUnavailableNoLocation: "Wetterdaten können ohne Standortinformationen nicht abgerufen werden.",
  currentWeatherInfoUnavailable: "Aktuelle Wetterinformationen konnten nicht abgerufen werden.",
  envDataUnavailableNoLocation: "Umweltdaten können ohne Standortinformationen nicht abgerufen werden.",
  ...PIPELINE_UI_STRINGS_INTERNAL[LanguageCode.DE],
};

const UI_STRINGS_ES: UiStrings = {
  tagline: "Su asistente inteligente para la salud de las plantas.",
  allRightsReserved: "© " + new Date().getFullYear() + " Fedai. Todos los derechos reservados.",
  selectLanguage: "Seleccionar Idioma",
  uploadImage: "Subir Imagen",
  captureImage: "Capturar con Cámara",
  clearImage: "Limpiar Imagen",
  imagePreview: "Vista Previa de Imagen",
  maxFileSizeError: (size) => `El tamaño máximo del archivo es ${size}MB. Por favor seleccione una imagen más pequeña.`,
  fileTypeNotAllowedError: (types) => `Tipo de archivo no permitido. Por favor seleccione uno de los siguientes tipos: ${types}.`,
  optionalDescriptionPlaceholder: "Información adicional sobre el estado de la planta (opcional)...",
  analyzeButton: "Analizar",
  analyzingButton: "Analizando...",
  locationInfoTitle: "Información de Ubicación",
  locationPermissionPromptMessage: "Necesitamos acceso a su ubicación para un análisis preciso y soluciones locales. Por favor conceda permiso de ubicación.",
  requestLocationPermissionButton: "Conceder Permiso de Ubicación",
  locationPermissionDeniedMessage: "Permiso de ubicación denegado. La ubicación aproximada se determinará mediante IP, o algunas funciones locales podrían no estar disponibles.",
  locationPermissionUnavailableMessage: "Los servicios de ubicación no están disponibles. Intentando determinar la ubicación aproximada mediante IP.",
  locationStatusFetching: "Obteniendo ubicación...",
  locationStatusSuccessGps: (lat, lon) => `Ubicación: Lat ${lat.toFixed(2)}, Lon ${lon.toFixed(2)} (GPS).`,
  locationStatusSuccessIp: (city, country, service) => `Ubicación aproximada: ${city}, ${country} (basada en IP vía ${service}).`,
  locationStatusError: "Error al obtener la ubicación. Por favor inténtelo más tarde o permita la ubicación basada en IP.",
  locationGpsSuccessMessage: "Ubicación precisa activa.",
  locationIpSuccessMessage: "Ubicación aproximada determinada.",
  locationErrorGeneral: "No se pudo determinar la ubicación. Por favor verifique su conexión a internet o inténtelo más tarde.",
  locationPermissionDeniedUserMessage: "Permiso de ubicación denegado. Se recomienda información de ubicación para un análisis local preciso.",
  locationPermissionUnavailableUserMessage: "Servicios de ubicación no disponibles. Se recomienda información de ubicación para un análisis local preciso.",
  fetchingIpLocation: "Obteniendo ubicación desde la dirección IP...",
  ipLocationSuccess: "Ubicación obtenida exitosamente desde la dirección IP.",
  ipLocationFailed: "Error al obtener la ubicación desde la dirección IP.",
  weatherTabCurrent: "Actual",
  weatherTabRecent: "Este Mes",
  weatherTabHistorical: "Prom. 5 Años",
  weatherFetching: "Obteniendo datos meteorológicos...",
  weatherUnavailable: "Datos meteorológicos no disponibles.",
  weatherLastUpdated: "Última Actualización",
  temperature: "Temperatura",
  humidity: "Humedad",
  precipitation: "Precipitación",
  windSpeed: "Velocidad del Viento",
  weatherCondition: "Condición Climática",
  meanTemperature: "Temp. Media",
  totalPrecipitation: "Precip. Total",
  fiveYearAverage: "Promedio de 5 Años",
  evapotranspirationLabel: "Evapotranspiración (ET₀)",
  evapotranspirationUnit: "mm/día",
  gddLabel: "Grados Día de Crecimiento (GDC)",
  gddUnit: "GDC",
  environmentalFactorsTitle: "Factores Ambientales",
  elevation: "Elevación",
  soilData: "Datos del Suelo",
  soilPH: "pH del Suelo",
  soilOrganicCarbon: "Carbono Orgánico",
  soilCEC: "Cap. Intercambio Catiónico (CIC)",
  soilNitrogen: "Nitrógeno Total",
  soilTextureLabel: "Textura del Suelo",
  soilSandLabel: "Arena",
  soilSiltLabel: "Limo",
  soilClayLabel: "Arcilla",
  soilAWCLabel: "Cap. Agua Disponible (CAD)",
  soilAWCUnit: "mm (0-5cm)",
  soilDataSourceNote: "Nota: Los datos del suelo son estimaciones del modelo SoilGrids. Se recomienda un análisis local del suelo para valores precisos.",
  fetchingEnvironmentalData: "Obteniendo datos ambientales...",
  environmentalDataUnavailable: "Datos ambientales no disponibles.",
  environmentalDataLastUpdated: "Última Actualización",
  apiError: "Error de API. Por favor inténtelo más tarde.",
  apiKeyMissingError: "Clave API no configurada. No se puede realizar el análisis.",
  analysisError: "Ocurrió un error durante el análisis. Por favor inténtelo de nuevo. Si el problema persiste, verifique el estado de los servicios o contacte con soporte.",
  noDiseaseFound: "No se Encontró Enfermedad o Imagen Insuficiente",
  diseaseNameLabel: "Nombre de la Enfermedad",
  definitionLabel: "Definición",
  possibleCausesLabel: "Posibles Causas",
  solutionsLabel: "Soluciones",
  technicalAssessmentLabel: "Evaluación Técnica de Fedai",
  similarPastCasesLabel: "Casos Anteriores Similares",
  solutionTypeCultural: "Cultural",
  solutionTypeBiological: "Biológica",
  solutionTypeChemicalGeneral: "Química (General)",
  solutionTypeObservation: "Observación",
  solutionTypePreventive: "Preventiva",
  solutionTypeFertilizerAdjustment: "Ajuste de Fertilizante",
  applicationNotesLabel: "Notas de Aplicación",
  solutionExampleBrandsLabel: "Marcas/Tipos de Producto de Ejemplo",
  solutionEstimatedBudgetLabel: "Presupuesto Estimado",
  consultLocalExperts: "Para tratamientos químicos, consulte a expertos agrícolas locales, cumpla con las regulaciones locales y use solo productos aprobados según las instrucciones de la etiqueta.",
  consultLocalExpertsSoil: "Para la fertilización, realice siempre pruebas de suelo locales y busque asesoramiento experto para cantidades precisas y productos adecuados.",
  dataConsideredLocation: "Datos de ubicación considerados.",
  dataConsideredWeather: "Datos meteorológicos considerados.",
  dataConsideredEnvironmental: "Datos ambientales (elevación/suelo) considerados.",
  followUpQuestionLabel: "Pregunta de Seguimiento",
  submitAnswerButton: "Enviar Respuesta",
  errorTitle: "Error",
  wmoWeatherCodes: {
    0: 'Cielo despejado', 1: 'Principalmente despejado', 2: 'Parcialmente nublado', 3: 'Cubierto',
    45: 'Niebla', 48: 'Niebla engelante',
    51: 'Llovizna ligera', 53: 'Llovizna moderada', 55: 'Llovizna densa',
    56: 'Llovizna helada ligera', 57: 'Llovizna helada densa',
    61: 'Lluvia ligera', 63: 'Lluvia moderada', 65: 'Lluvia fuerte',
    66: 'Lluvia helada ligera', 67: 'Lluvia helada fuerte',
    71: 'Nevada ligera', 73: 'Nevada moderada', 75: 'Nevada fuerte',
    77: 'Granos de nieve',
    80: 'Chubascos ligeros', 81: 'Chubascos moderados', 82: 'Chubascos violentos',
    85: 'Chubascos de nieve ligeros', 86: 'Chubascos de nieve fuertes',
    95: 'Tormenta', 96: 'Tormenta con granizo ligero', 99: 'Tormenta con granizo fuerte'
  },
  serviceStatusTitle: "Estado del Servicio",
  serviceStatusUp: "Activo",
  serviceStatusDown: "Inactivo",
  serviceStatusError: "Error",
  serviceStatusPending: "Pendiente...",
  serviceLocation: "Servicio de Ubicación",
  serviceWeather: "Servicio Meteorológico",
  serviceElevation: "Servicio de Elevación",
  serviceSoil: "Servicio de Datos del Suelo",
  serviceAI: "Servicio de Análisis IA",
  aiAnalysisInProgressMessage: "El análisis de IA está en curso. Este paso puede tomar unos momentos, especialmente para imágenes complejas o datos contextuales detallados.",
  solutionEstimatedBudgetLow: "Bajo",
  solutionEstimatedBudgetMedium: "Medio",
  solutionEstimatedBudgetHigh: "Alto",
  solutionEstimatedBudgetUnknown: "Desconocido",
  photoTipsTitle: "Consejos para Fotos",
  photoTipsContent: "Para un buen análisis:\n- Capture una imagen clara de la hoja/área afectada.\n- Asegure una buena iluminación.\n- Si es posible, tome una foto de toda la planta y un primer plano del síntoma.",
  showPhotoGuidelines: "Mostrar Guías para Fotos",
  hidePhotoGuidelines: "Ocultar Guías para Fotos",
  photoGuidelineGoodLight: "Buena Iluminación: La luz natural brillante e indirecta es la mejor. Evite sombras fuertes o luz solar directa.",
  photoGuidelineClearFocus: "Enfoque Claro: Asegúrese de que los síntomas estén nítidos. Las fotos borrosas dificultan el análisis.",
  photoGuidelineAffectedPart: "Parte Afectada: Enfóquese principalmente en la hoja, tallo o fruto que muestra síntomas.",
  photoGuidelineWholePlantContext: "Contexto General de la Planta: Si es posible, incluya también una foto que muestre la planta completa.",
  photoGuidelineAvoidClutter: "Evite el Desorden: Mantenga el fondo simple para que la planta destaque.",
  photoGuidelineMultipleAngles: "Múltiples Ángulos: Varias fotos desde diferentes ángulos pueden ser útiles, especialmente para problemas complejos.",
  whyLocationImportantTitle: "¿Por Qué es Importante la Ubicación?",
  whyLocationImportantContent: "Su ubicación nos ayuda a proporcionar análisis y soluciones más precisos al considerar patrones climáticos locales, enfermedades comunes y prácticas agrícolas regionales.",
  whyEnvironmentalDataImportantTitle: "¿Por Qué son Importantes los Datos Ambientales?",
  whyEnvironmentalDataImportantContent: "Factores ambientales como la elevación y el tipo de suelo afectan la salud de las plantas y la susceptibilidad a enfermedades. Estos datos mejoran la precisión del análisis.",
  technicalAssessmentExplanationTitle: "¿Qué es la Evaluación Técnica?",
  technicalAssessmentExplanationContent: "En esta sección, Fedai explica cómo interpretó la imagen proporcionada y los datos contextuales (clima, suelo, etc.) para llegar al diagnóstico. Destaca qué factores fueron significativos y cómo se relacionan con la posible enfermedad.",
  noDiseaseGuidanceTitle: "Próximos Pasos",
  noDiseaseGuidanceInsufficientImage: "No se pudo realizar un diagnóstico claro debido a la calidad insuficiente de la imagen.\n- Intente subir una foto más clara, bien iluminada y enfocada en los síntomas.\n- Continúe observando su planta y vuelva a analizar si los síntomas cambian.",
  noDiseaseGuidancePlantHealthy: "¡Su planta parece sana! No se detectó ninguna enfermedad significativa.\n- Continúe con su rutina de cuidado de plantas.\n- Puede volver a analizar si nota algún cambio.",
  noDiseaseGuidanceGeneralSymptoms: "No se pudo realizar un diagnóstico específico ya que los síntomas son generales o muy tempranos.\n- Observe su planta durante unos días más. Vuelva a analizar con una foto nueva si los síntomas se vuelven más distintivos o empeoran.\n- Si las preocupaciones persisten, consulte a un vivero local o a un experto agrícola.",
  noDiseaseGuidanceObservationPrompt: "Continúe observando. Si los síntomas cambian o empeoran, vuelva a analizar con una foto nueva o consulte a un experto.",
  differentialDiagnosesLabel: "Diagnósticos Diferenciales",
  imageQualityNotesLabel: "Notas sobre la Calidad de la Imagen",
  qualitativeConfidenceLabel: "Confianza del Diagnóstico",
  dataSourceDisclaimer: "El análisis se basa en modelos de datos disponibles públicamente. Las pruebas locales son el estándar de oro para la precisión.",
  errorNetwork: "No se pudo conectar. Por favor verifique su conexión a internet e inténtelo de nuevo.",
  errorJsonParse: "Hubo un problema al procesar la respuesta de la IA. Por favor inténtelo de nuevo.",
  errorRateLimit: "Demasiadas solicitudes. Por favor espere un momento e inténtelo de nuevo.",
  errorAnalysisGeneric: "Ocurrió un error inesperado durante el análisis. Por favor inténtelo de nuevo.",
  errorAnalysisTimeout: "El análisis está tardando más de lo esperado. Por favor, compruebe su conexión de red o inténtelo de nuevo más tarde.",
  startDiagnosisButton: "Iniciar Diagnóstico de Planta",
  thinkingTextAfterImageUpload: "Genial, estoy mirando tu foto. Ahora, revisemos el entorno local para un diagnóstico más preciso...",
  viewMoreDetailsButton: "Ver Más Detalles",
  hideMoreDetailsButton: "Ocultar Detalles",
  summaryTab: "Resumen",
  solutionsTab: "Soluciones",
  technicalDetailsTab: "Detalles Técnicos",
  confidenceLevelLabel: "Nivel de Confianza",
  confidenceHigh: "Alta",
  confidenceMedium: "Media",
  confidenceLow: "Baja",
  confidenceUnknown: "Desconocida",
  weatherSummaryTitle: "Resumen del Clima",
  environmentalSummaryTitle: "Resumen Ambiental",
  currentMonthTempTrend: "Tendencia de Temp. de Este Mes",
  backendDashboardTitle: "Gestión de Servicios Backend",
  serviceProviderLabel: "Proveedor(es)",
  apiKeyManagementLabel: "Gestión de Claves API",
  statusLabel: "Estado",
  aiServiceTitle: "Servicio de Análisis IA (Google Gemini)",
  geminiModelInfo: "Modelo: gemini-2.5-flash-preview-04-17",
  geminiKeyInfo: "Gestionada de forma segura por el proxy backend mediante archivo .env.",
  ipLocationServiceTitle: "Servicio de Ubicación IP",
  ipLocationProvidersInfo: "Proveedores: ipapi.co (Principal), ip-api.com (Respaldo) - vía Proxy",
  ipLocationKeyInfo: "Usa APIs públicas. Gestión de claves vía proxy si es requerido por futuros proveedores.",
  weatherServiceTitle: "Servicio Meteorológico",
  weatherProviderInfo: "Proveedor: Open-Meteo - vía Proxy",
  weatherKeyInfo: "Usa APIs públicas. Gestión de claves vía proxy si es requerido por futuros proveedores.",
  elevationServiceTitle: "Servicio de Elevación",
  elevationProvidersInfo: "Proveedores: Open-Elevation (Principal), OpenTopoData (Respaldo) - vía Proxy",
  elevationKeyInfo: "Usa APIs públicas. Gestión de claves vía proxy si es requerido por futuros proveedores.",
  soilServiceTitle: "Servicio de Datos del Suelo",
  soilProviderInfo: "Proveedor: SoilGrids - vía Proxy",
  soilKeyInfo: "Usa APIs públicas. Gestión de claves vía proxy si es requerido por futuros proveedores.",
  howToUpdateConfigText: "Nota: Para cambiar los proveedores de servicios o las configuraciones del backend, actualice el archivo `server.js` del proxy backend o las variables de entorno según sea necesario, y reinicie el servidor proxy. Este panel es para fines informativos.",
  switchToDiagnosisViewButton: "Volver a Diagnóstico",
  switchToDashboardViewButton: "Servicios Backend",
  leaveDiagnosisConfirmationTitle: "¿Salir del Diagnóstico?",
  leaveDiagnosisConfirmationMessage: "Tiene un diagnóstico en curso. ¿Está seguro de que desea salir? Su imagen y datos actuales se borrarán.",
  confirmButtonLabel: "Confirmar",
  cancelButtonLabel: "Cancelar",

  // Newly added for centralization
  yourLocation: "Su Ubicación",
  localEnvironmentInsightsTitle: "Información del Entorno Local",
  typeYourAnswerPlaceholder: "Escriba su respuesta aquí...",
  noSpecificSolutionsFoundTitle: "No se Encontraron Soluciones Específicas",
  noSpecificSolutionsFoundMessage: "No hay recomendaciones de soluciones directas para este diagnóstico. Continúe con el cuidado general de la planta y la observación, o inténtelo de nuevo con una imagen diferente.",
  weatherDataUnavailableNoLocation: "Los datos meteorológicos no se pueden obtener sin información de ubicación.",
  currentWeatherInfoUnavailable: "No se pudo recuperar la información meteorológica actual.",
  envDataUnavailableNoLocation: "Los datos ambientales no se pueden obtener sin información de ubicación.",
  ...PIPELINE_UI_STRINGS_INTERNAL[LanguageCode.ES],
};

const UI_STRINGS_PT: UiStrings = {
  tagline: "Seu assistente inteligente para a saúde das plantas.",
  allRightsReserved: "© " + new Date().getFullYear() + " Fedai. Todos os direitos reservados.",
  selectLanguage: "Selecionar Idioma",
  uploadImage: "Carregar Imagem",
  captureImage: "Capturar com Câmera",
  clearImage: "Limpar Imagem",
  imagePreview: "Pré-visualização da Imagem",
  maxFileSizeError: (size) => `O tamanho máximo do arquivo é ${size}MB. Por favor, selecione uma imagem menor.`,
  fileTypeNotAllowedError: (types) => `Tipo de arquivo não permitido. Por favor, selecione um dos seguintes tipos: ${types}.`,
  optionalDescriptionPlaceholder: "Informações adicionais sobre a condição da planta (opcional)...",
  analyzeButton: "Analisar",
  analyzingButton: "Analisando...",
  locationInfoTitle: "Informações de Localização",
  locationPermissionPromptMessage: "Precisamos de acesso à sua localização para análises precisas e soluções locais. Por favor, conceda permissão de localização.",
  requestLocationPermissionButton: "Conceder Permissão de Localização",
  locationPermissionDeniedMessage: "Permissão de localização negada. A localização aproximada será determinada via IP, ou alguns recursos locais podem estar indisponíveis.",
  locationPermissionUnavailableMessage: "Serviços de localização indisponíveis. Tentando determinar a localização aproximada via IP.",
  locationStatusFetching: "Obtendo localização...",
  locationStatusSuccessGps: (lat, lon) => `Localização: Lat ${lat.toFixed(2)}, Lon ${lon.toFixed(2)} (GPS).`,
  locationStatusSuccessIp: (city, country, service) => `Localização aproximada: ${city}, ${country} (baseada em IP via ${service}).`,
  locationStatusError: "Falha ao obter localização. Por favor, tente novamente mais tarde ou permita localização baseada em IP.",
  locationGpsSuccessMessage: "Localização precisa ativa.",
  locationIpSuccessMessage: "Localização aproximada determinada.",
  locationErrorGeneral: "Não foi possível determinar a localização. Por favor, verifique sua conexão com a internet ou tente novamente mais tarde.",
  locationPermissionDeniedUserMessage: "Permissão de localização negada. Informações de localização são recomendadas para análises locais precisas.",
  locationPermissionUnavailableUserMessage: "Serviços de localização indisponíveis. Informações de localização são recomendadas para análises locais precisas.",
  fetchingIpLocation: "Obtendo localização do endereço IP...",
  ipLocationSuccess: "Localização obtida com sucesso do endereço IP.",
  ipLocationFailed: "Falha ao obter localização do endereço IP.",
  weatherTabCurrent: "Atual",
  weatherTabRecent: "Este Mês",
  weatherTabHistorical: "Média 5 Anos",
  weatherFetching: "Obtendo dados meteorológicos...",
  weatherUnavailable: "Dados meteorológicos indisponíveis.",
  weatherLastUpdated: "Última Atualização",
  temperature: "Temperatura",
  humidity: "Umidade",
  precipitation: "Precipitação",
  windSpeed: "Velocidade do Vento",
  weatherCondition: "Condição Climática",
  meanTemperature: "Temp. Média",
  totalPrecipitation: "Precip. Total",
  fiveYearAverage: "Média de 5 Anos",
  evapotranspirationLabel: "Evapotranspiração (ET₀)",
  evapotranspirationUnit: "mm/dia",
  gddLabel: "Graus-Dia de Crescimento (GDC)",
  gddUnit: "GDC",
  environmentalFactorsTitle: "Fatores Ambientais",
  elevation: "Elevação",
  soilData: "Dados do Solo",
  soilPH: "pH do Solo",
  soilOrganicCarbon: "Carbono Orgânico",
  soilCEC: "Cap. Troca Catiônica (CTC)",
  soilNitrogen: "Nitrogênio Total",
  soilTextureLabel: "Textura do Solo",
  soilSandLabel: "Areia",
  soilSiltLabel: "Silte",
  soilClayLabel: "Argila",
  soilAWCLabel: "Cap. Água Disponível (CAD)",
  soilAWCUnit: "mm (0-5cm)",
  soilDataSourceNote: "Nota: Os dados do solo são estimativas do modelo SoilGrids. Análises locais do solo são recomendadas para valores precisos.",
  fetchingEnvironmentalData: "Obtendo dados ambientais...",
  environmentalDataUnavailable: "Dados ambientais indisponíveis.",
  environmentalDataLastUpdated: "Última Atualização",
  apiError: "Erro de API. Por favor, tente novamente mais tarde.",
  apiKeyMissingError: "Chave de API não configurada. Não é possível realizar a análise.",
  analysisError: "Ocorreu um erro durante a análise. Por favor, tente novamente. Se o problema persistir, verifique o status dos serviços ou entre em contato com o suporte.",
  noDiseaseFound: "Nenhuma Doença Encontrada ou Imagem Insuficiente",
  diseaseNameLabel: "Nome da Doença",
  definitionLabel: "Definição",
  possibleCausesLabel: "Causas Possíveis",
  solutionsLabel: "Soluções",
  technicalAssessmentLabel: "Avaliação Técnica Fedai",
  similarPastCasesLabel: "Casos Anteriores Semelhantes",
  solutionTypeCultural: "Cultural",
  solutionTypeBiological: "Biológica",
  solutionTypeChemicalGeneral: "Química (Geral)",
  solutionTypeObservation: "Observação",
  solutionTypePreventive: "Preventiva",
  solutionTypeFertilizerAdjustment: "Ajuste de Fertilizante",
  applicationNotesLabel: "Notas de Aplicação",
  solutionExampleBrandsLabel: "Marcas/Tipos de Produto Exemplo",
  solutionEstimatedBudgetLabel: "Orçamento Estimado",
  consultLocalExperts: "Para tratamentos químicos, consulte especialistas agrícolas locais, siga as regulamentações locais e use apenas produtos aprovados de acordo com as instruções do rótulo.",
  consultLocalExpertsSoil: "Para fertilização, sempre realize testes de solo locais e procure aconselhamento especializado para quantidades precisas e produtos adequados.",
  dataConsideredLocation: "Dados de localização considerados.",
  dataConsideredWeather: "Dados meteorológicos considerados.",
  dataConsideredEnvironmental: "Dados ambientais (elevação/solo) considerados.",
  followUpQuestionLabel: "Pergunta de Acompanhamento",
  submitAnswerButton: "Enviar Resposta",
  errorTitle: "Erro",
  wmoWeatherCodes: {
    0: 'Céu limpo', 1: 'Principalmente limpo', 2: 'Parcialmente nublado', 3: 'Encoberto',
    45: 'Nevoeiro', 48: 'Nevoeiro gelado',
    51: 'Chuvisco leve', 53: 'Chuvisco moderado', 55: 'Chuvisco forte',
    56: 'Chuvisco gelado leve', 57: 'Chuvisco gelado forte',
    61: 'Chuva fraca', 63: 'Chuva moderada', 65: 'Chuva forte',
    66: 'Chuva gelada fraca', 67: 'Chuva gelada forte',
    71: 'Neve fraca', 73: 'Neve moderada', 75: 'Neve forte',
    77: 'Grãos de neve',
    80: 'Aguaceiros fracos', 81: 'Aguaceiros moderados', 82: 'Aguaceiros violentos',
    85: 'Aguaceiros de neve fracos', 86: 'Aguaceiros de neve fortes',
    95: 'Trovoada', 96: 'Trovoada com granizo fraco', 99: 'Trovoada com granizo forte'
  },
  serviceStatusTitle: "Status do Serviço",
  serviceStatusUp: "Ativo",
  serviceStatusDown: "Inativo",
  serviceStatusError: "Erro",
  serviceStatusPending: "Pendente...",
  serviceLocation: "Serviço de Localização",
  serviceWeather: "Serviço Meteorológico",
  serviceElevation: "Serviço de Elevação",
  serviceSoil: "Serviço de Dados do Solo",
  serviceAI: "Serviço de Análise IA",
  aiAnalysisInProgressMessage: "A análise de IA está em andamento. Esta etapa pode levar alguns instantes, especialmente para imagens complexas ou dados contextuais detalhados.",
  solutionEstimatedBudgetLow: "Baixo",
  solutionEstimatedBudgetMedium: "Médio",
  solutionEstimatedBudgetHigh: "Alto",
  solutionEstimatedBudgetUnknown: "Desconhecido",
  photoTipsTitle: "Dicas de Fotografia",
  photoTipsContent: "Para uma boa análise:\n- Capture uma imagem nítida da folha/área afetada.\n- Garanta boa iluminação.\n- Se possível, tire uma foto da planta inteira e um close-up do sintoma.",
  showPhotoGuidelines: "Mostrar Diretrizes de Foto",
  hidePhotoGuidelines: "Ocultar Diretrizes de Foto",
  photoGuidelineGoodLight: "Boa Iluminação: Luz natural brilhante e indireta é a melhor. Evite sombras fortes ou luz solar direta.",
  photoGuidelineClearFocus: "Foco Nítido: Certifique-se de que os sintomas estejam em foco. Fotos embaçadas dificultam a análise.",
  photoGuidelineAffectedPart: "Parte Afetada: Concentre-se principalmente na folha, caule ou fruto que apresenta sintomas.",
  photoGuidelineWholePlantContext: "Contexto Geral da Planta: Se possível, inclua também uma foto mostrando a planta inteira.",
  photoGuidelineAvoidClutter: "Evite Desordem: Mantenha o fundo simples para que a planta se destaque.",
  photoGuidelineMultipleAngles: "Múltiplos Ângulos: Algumas fotos de ângulos diferentes podem ser úteis, especialmente para problemas complexos.",
  whyLocationImportantTitle: "Por Que a Localização é Importante?",
  whyLocationImportantContent: "Sua localização nos ajuda a fornecer análises e soluções mais precisas, considerando padrões climáticos locais, doenças comuns e práticas agrícolas regionais.",
  whyEnvironmentalDataImportantTitle: "Por Que os Dados Ambientais São Importantes?",
  whyEnvironmentalDataImportantContent: "Fatores ambientais como elevação e tipo de solo afetam a saúde das plantas e a suscetibilidade a doenças. Esses dados aumentam a precisão da análise.",
  technicalAssessmentExplanationTitle: "O Que é Avaliação Técnica?",
  technicalAssessmentExplanationContent: "Nesta seção, o Fedai explica como interpretou a imagem fornecida e os dados contextuais (clima, solo, etc.) para chegar ao diagnóstico. Destaca quais fatores foram significativos e como eles se relacionam com a doença potencial.",
  noDiseaseGuidanceTitle: "Próximos Passos",
  noDiseaseGuidanceInsufficientImage: "Não foi possível fazer um diagnóstico claro devido à qualidade insuficiente da imagem.\n- Tente carregar uma foto mais nítida, bem iluminada e focada nos sintomas.\n- Continue observando sua planta e reanalise se os sintomas mudarem.",
  noDiseaseGuidancePlantHealthy: "Sua planta parece saudável! Nenhuma doença significativa foi detectada.\n- Continue com sua rotina de cuidados com as plantas.\n- Você pode reanalisar se notar alguma alteração.",
  noDiseaseGuidanceGeneralSymptoms: "Não foi possível fazer um diagnóstico específico, pois os sintomas são gerais ou muito precoces.\n- Observe sua planta por mais alguns dias. Reanalise com uma nova foto se os sintomas se tornarem mais distintos ou piorarem.\n- Se as preocupações persistirem, consulte um viveiro local ou um especialista agrícola.",
  noDiseaseGuidanceObservationPrompt: "Continue observando. Se os sintomas mudarem ou piorarem, reanalise com uma nova foto ou consulte um especialista.",
  differentialDiagnosesLabel: "Diagnósticos Diferenciais",
  imageQualityNotesLabel: "Notas sobre a Qualidade da Imagem",
  qualitativeConfidenceLabel: "Confiança do Diagnóstico",
  dataSourceDisclaimer: "A análise é baseada em modelos de dados disponíveis publicamente. Testes locais são o padrão ouro para precisão.",
  errorNetwork: "Não foi possível conectar. Por favor, verifique sua conexão com a internet e tente novamente.",
  errorJsonParse: "Houve um problema ao processar a resposta da IA. Por favor, tente novamente.",
  errorRateLimit: "Muitas solicitações. Por favor, aguarde um momento e tente novamente.",
  errorAnalysisGeneric: "Ocorreu um erro inesperado durante a análise. Por favor, tente novamente.",
  errorAnalysisTimeout: "A análise está demorando mais do que o esperado. Verifique sua conexão de rede ou tente novamente mais tarde.",
  startDiagnosisButton: "Iniciar Diagnóstico de Planta",
  thinkingTextAfterImageUpload: "Ótimo, estou olhando sua foto. Agora, vamos verificar o ambiente local para um diagnóstico mais preciso...",
  viewMoreDetailsButton: "Ver Mais Detalhes",
  hideMoreDetailsButton: "Ocultar Detalhes",
  summaryTab: "Resumo",
  solutionsTab: "Soluções",
  technicalDetailsTab: "Detalhes Técnicos",
  confidenceLevelLabel: "Nível de Confiança",
  confidenceHigh: "Alta",
  confidenceMedium: "Moderada",
  confidenceLow: "Baixa",
  confidenceUnknown: "Desconhecida",
  weatherSummaryTitle: "Resumo do Clima",
  environmentalSummaryTitle: "Resumo Ambiental",
  currentMonthTempTrend: "Tendência de Temp. Deste Mês",
  backendDashboardTitle: "Gerenciamento de Serviços Backend",
  serviceProviderLabel: "Provedor(es)",
  apiKeyManagementLabel: "Gerenciamento de Chave API",
  statusLabel: "Status",
  aiServiceTitle: "Serviço de Análise IA (Google Gemini)",
  geminiModelInfo: "Modelo: gemini-2.5-flash-preview-04-17",
  geminiKeyInfo: "Gerenciado com segurança pelo proxy backend via arquivo .env.",
  ipLocationServiceTitle: "Serviço de Localização IP",
  ipLocationProvidersInfo: "Provedores: ipapi.co (Primário), ip-api.com (Fallback) - via Proxy",
  ipLocationKeyInfo: "Usa APIs públicas. Gerenciamento de chaves via proxy se exigido por futuros provedores.",
  weatherServiceTitle: "Serviço Meteorológico",
  weatherProviderInfo: "Provedor: Open-Meteo - via Proxy",
  weatherKeyInfo: "Usa APIs públicas. Gerenciamento de chaves via proxy se exigido por futuros provedores.",
  elevationServiceTitle: "Serviço de Elevação",
  elevationProvidersInfo: "Provedores: Open-Elevation (Primário), OpenTopoData (Fallback) - via Proxy",
  elevationKeyInfo: "Usa APIs públicas. Gerenciamento de chaves via proxy se exigido por futuros provedores.",
  soilServiceTitle: "Serviço de Dados do Solo",
  soilProviderInfo: "Provedor: SoilGrids - via Proxy",
  soilKeyInfo: "Usa APIs públicas. Gerenciamento de chaves via proxy se exigido por futuros provedores.",
  howToUpdateConfigText: "Nota: Para alterar provedores de serviço ou configurações de backend, atualize o arquivo `server.js` do proxy backend ou as variáveis de ambiente conforme necessário e reinicie o servidor proxy. Este painel é para fins informativos.",
  switchToDiagnosisViewButton: "Voltar ao Diagnóstico",
  switchToDashboardViewButton: "Serviços Backend",
  leaveDiagnosisConfirmationTitle: "Sair do Diagnóstico?",
  leaveDiagnosisConfirmationMessage: "Você tem um diagnóstico em andamento. Tem certeza que deseja sair? Sua imagem e dados atuais serão apagados.",
  confirmButtonLabel: "Confirmar",
  cancelButtonLabel: "Cancelar",

  // Newly added for centralization
  yourLocation: "Sua Localização",
  localEnvironmentInsightsTitle: "Informações do Ambiente Local",
  typeYourAnswerPlaceholder: "Digite sua resposta aqui...",
  noSpecificSolutionsFoundTitle: "Nenhuma Solução Específica Encontrada",
  noSpecificSolutionsFoundMessage: "Não há recomendações de soluções diretas para este diagnóstico. Continue com os cuidados gerais da planta e observação, ou tente novamente com uma imagem diferente.",
  weatherDataUnavailableNoLocation: "Os dados meteorológicos não podem ser obtidos sem informações de localização.",
  currentWeatherInfoUnavailable: "As informações meteorológicas atuais não puderam ser recuperadas.",
  envDataUnavailableNoLocation: "Os dados ambientais não podem ser obtidos sem informações de localização.",
  ...PIPELINE_UI_STRINGS_INTERNAL[LanguageCode.PT],
};

const UI_STRINGS_FR: UiStrings = {
  tagline: "Votre assistant intelligent pour la santé des plantes.",
  allRightsReserved: "© " + new Date().getFullYear() + " Fedai. Tous droits réservés.",
  selectLanguage: "Choisir la Langue",
  uploadImage: "Télécharger une Image",
  captureImage: "Prendre une Photo",
  clearImage: "Effacer l'Image",
  imagePreview: "Aperçu de l'Image",
  maxFileSizeError: (size) => `La taille maximale du fichier est de ${size}Mo. Veuillez sélectionner une image plus petite.`,
  fileTypeNotAllowedError: (types) => `Type de fichier non autorisé. Veuillez sélectionner l'un des types suivants : ${types}.`,
  optionalDescriptionPlaceholder: "Informations supplémentaires sur l'état de la plante (facultatif)...",
  analyzeButton: "Analyser",
  analyzingButton: "Analyse en cours...",
  locationInfoTitle: "Informations de Localisation",
  locationPermissionPromptMessage: "Nous avons besoin d'accéder à votre localisation pour une analyse précise et des solutions locales. Veuillez accorder la permission de localisation.",
  requestLocationPermissionButton: "Accorder la Permission de Localisation",
  locationPermissionDeniedMessage: "Permission de localisation refusée. La localisation approximative sera déterminée via IP, ou certaines fonctionnalités locales pourraient ne pas être disponibles.",
  locationPermissionUnavailableMessage: "Les services de localisation ne sont pas disponibles. Tentative de détermination de la localisation approximative via IP.",
  locationStatusFetching: "Obtention de la localisation...",
  locationStatusSuccessGps: (lat, lon) => `Localisation : Lat ${lat.toFixed(2)}, Lon ${lon.toFixed(2)} (GPS).`,
  locationStatusSuccessIp: (city, country, service) => `Localisation approximative : ${city}, ${country} (basée sur IP via ${service}).`,
  locationStatusError: "Échec de l'obtention de la localisation. Veuillez réessayer plus tard ou autoriser la localisation basée sur IP.",
  locationGpsSuccessMessage: "Localisation précise active.",
  locationIpSuccessMessage: "Localisation approximative déterminée.",
  locationErrorGeneral: "Impossible de déterminer la localisation. Veuillez vérifier votre connexion internet ou réessayer plus tard.",
  locationPermissionDeniedUserMessage: "Permission de localisation refusée. Les informations de localisation sont recommandées pour une analyse locale précise.",
  locationPermissionUnavailableUserMessage: "Services de localisation non disponibles. Les informations de localisation sont recommandées pour une analyse locale précise.",
  fetchingIpLocation: "Obtention de la localisation depuis l'adresse IP...",
  ipLocationSuccess: "Localisation obtenue avec succès depuis l'adresse IP.",
  ipLocationFailed: "Échec de l'obtention de la localisation depuis l'adresse IP.",
  weatherTabCurrent: "Actuel",
  weatherTabRecent: "Ce Mois",
  weatherTabHistorical: "Moy. 5 Ans",
  weatherFetching: "Obtention des données météo...",
  weatherUnavailable: "Données météo non disponibles.",
  weatherLastUpdated: "Dernière Mise à Jour",
  temperature: "Température",
  humidity: "Humidité",
  precipitation: "Précipitations",
  windSpeed: "Vitesse du Vent",
  weatherCondition: "Condition Météo",
  meanTemperature: "Temp. Moyenne",
  totalPrecipitation: "Précip. Totales",
  fiveYearAverage: "Moyenne sur 5 Ans",
  evapotranspirationLabel: "Évapotranspiration (ET₀)",
  evapotranspirationUnit: "mm/jour",
  gddLabel: "Degrés-Jours de Croissance (DJC)",
  gddUnit: "DJC",
  environmentalFactorsTitle: "Facteurs Environnementaux",
  elevation: "Élévation",
  soilData: "Données du Sol",
  soilPH: "pH du Sol",
  soilOrganicCarbon: "Carbone Organique",
  soilCEC: "Cap. d'Échange Cationique (CEC)",
  soilNitrogen: "Azote Total",
  soilTextureLabel: "Texture du Sol",
  soilSandLabel: "Sable",
  soilSiltLabel: "Limon",
  soilClayLabel: "Argile",
  soilAWCLabel: "Cap. en Eau Utile (RFU)",
  soilAWCUnit: "mm (0-5cm)",
  soilDataSourceNote: "Note : Les données du sol sont des estimations du modèle SoilGrids. Une analyse locale du sol est recommandée pour des valeurs précises.",
  fetchingEnvironmentalData: "Obtention des données environnementales...",
  environmentalDataUnavailable: "Données environnementales non disponibles.",
  environmentalDataLastUpdated: "Dernière Mise à Jour",
  apiError: "Erreur API. Veuillez réessayer plus tard.",
  apiKeyMissingError: "Clé API non configurée. Impossible d'effectuer l'analyse.",
  analysisError: "Une erreur est survenue lors de l'analyse. Veuillez réessayer. Si le problème persiste, vérifiez l'état des services ou contactez le support.",
  noDiseaseFound: "Aucune Maladie Trouvée ou Image Insuffisante",
  diseaseNameLabel: "Nom de la Maladie",
  definitionLabel: "Définition",
  possibleCausesLabel: "Causes Possibles",
  solutionsLabel: "Solutions",
  technicalAssessmentLabel: "Évaluation Technique Fedai",
  similarPastCasesLabel: "Cas Antérieurs Similaires",
  solutionTypeCultural: "Culturelle",
  solutionTypeBiological: "Biologique",
  solutionTypeChemicalGeneral: "Chimique (Général)",
  solutionTypeObservation: "Observation",
  solutionTypePreventive: "Préventive",
  solutionTypeFertilizerAdjustment: "Ajustement de Fertilisant",
  applicationNotesLabel: "Notes d'Application",
  solutionExampleBrandsLabel: "Exemples de Marques/Types de Produits",
  solutionEstimatedBudgetLabel: "Budget Estimé",
  consultLocalExperts: "Pour les traitements chimiques, consultez des experts agricoles locaux, respectez les réglementations locales et utilisez uniquement des produits approuvés conformément aux instructions de l'étiquette.",
  consultLocalExpertsSoil: "Pour la fertilisation, effectuez toujours des analyses de sol locales et demandez l'avis d'experts pour des quantités précises et des produits adaptés.",
  dataConsideredLocation: "Données de localisation prises en compte.",
  dataConsideredWeather: "Données météorologiques prises en compte.",
  dataConsideredEnvironmental: "Données environnementales (élévation/sol) prises en compte.",
  followUpQuestionLabel: "Question de Suivi",
  submitAnswerButton: "Soumettre la Réponse",
  errorTitle: "Erreur",
  wmoWeatherCodes: {
    0: 'Ciel dégagé', 1: 'Principalement dégagé', 2: 'Partiellement nuageux', 3: 'Couvert',
    45: 'Brouillard', 48: 'Brouillard givrant',
    51: 'Bruine légère', 53: 'Bruine modérée', 55: 'Bruine forte',
    56: 'Bruine verglaçante légère', 57: 'Bruine verglaçante forte',
    61: 'Pluie faible', 63: 'Pluie modérée', 65: 'Pluie forte',
    66: 'Pluie verglaçante faible', 67: 'Pluie verglaçante forte',
    71: 'Chute de neige faible', 73: 'Chute de neige modérée', 75: 'Chute de neige forte',
    77: 'Neige en grains',
    80: 'Averses de pluie faibles', 81: 'Averses de pluie modérées', 82: 'Averses de pluie violentes',
    85: 'Averses de neige faibles', 86: 'Averses de neige fortes',
    95: 'Orage', 96: 'Orage avec grêle faible', 99: 'Orage avec grêle forte'
  },
  serviceStatusTitle: "État du Service",
  serviceStatusUp: "Actif",
  serviceStatusDown: "Inactif",
  serviceStatusError: "Erreur",
  serviceStatusPending: "En attente...",
  serviceLocation: "Service de Localisation",
  serviceWeather: "Service Météo",
  serviceElevation: "Service d'Élévation",
  serviceSoil: "Service de Données du Sol",
  serviceAI: "Service d'Analyse IA",
  aiAnalysisInProgressMessage: "L'analyse IA est en cours. Cette étape peut prendre quelques instants, notamment pour les images complexes ou les données contextuelles détaillées.",
  solutionEstimatedBudgetLow: "Faible",
  solutionEstimatedBudgetMedium: "Moyen",
  solutionEstimatedBudgetHigh: "Élevé",
  solutionEstimatedBudgetUnknown: "Inconnu",
  photoTipsTitle: "Conseils Photo",
  photoTipsContent: "Pour une bonne analyse :\n- Prenez une photo nette de la feuille/zone affectée.\n- Assurez un bon éclairage.\n- Si possible, prenez une photo de la plante entière et un gros plan du symptôme.",
  showPhotoGuidelines: "Afficher les Conseils Photo",
  hidePhotoGuidelines: "Masquer les Conseils Photo",
  photoGuidelineGoodLight: "Bon Éclairage : Une lumière naturelle vive et indirecte est préférable. Évitez les ombres dures ou la lumière directe du soleil.",
  photoGuidelineClearFocus: "Mise au Point Nette : Assurez-vous que les symptômes sont nets. Les photos floues rendent l'analyse difficile.",
  photoGuidelineAffectedPart: "Partie Affectée : Concentrez-vous principalement sur la feuille, la tige ou le fruit qui présente des symptômes.",
  photoGuidelineWholePlantContext: "Contexte Général de la Plante : Si possible, incluez également une photo montrant la plante entière.",
  photoGuidelineAvoidClutter: "Évitez le Désordre : Gardez l'arrière-plan simple pour que la plante ressorte.",
  photoGuidelineMultipleAngles: "Angles Multiples : Quelques photos sous différents angles peuvent être utiles, surtout pour les problèmes complexes.",
  whyLocationImportantTitle: "Pourquoi la Localisation est-elle Importante ?",
  whyLocationImportantContent: "Votre localisation nous aide à fournir une analyse et des solutions plus précises en tenant compte des conditions météorologiques locales, des maladies courantes et des pratiques agricoles régionales.",
  whyEnvironmentalDataImportantTitle: "Pourquoi les Données Environnementales sont-elles Importantes ?",
  whyEnvironmentalDataImportantContent: "Les facteurs environnementaux tels que l'élévation et le type de sol affectent la santé des plantes et leur sensibilité aux maladies. Ces données améliorent la précision de l'analyse.",
  technicalAssessmentExplanationTitle: "Qu'est-ce que l'Évaluation Technique ?",
  technicalAssessmentExplanationContent: "Dans cette section, Fedai explique comment il a interprété l'image fournie et les données contextuelles (météo, sol, etc.) pour parvenir au diagnostic. Il souligne quels facteurs ont été significatifs et comment ils se rapportent à la maladie potentielle.",
  noDiseaseGuidanceTitle: "Prochaines Étapes",
  noDiseaseGuidanceInsufficientImage: "Un diagnostic clair n'a pas pu être établi en raison d'une qualité d'image insuffisante.\n- Essayez de télécharger une photo plus claire, bien éclairée et axée sur les symptômes.\n- Continuez à observer votre plante et réanalysez si les symptômes changent.",
  noDiseaseGuidancePlantHealthy: "Votre plante semble en bonne santé ! Aucune maladie significative n'a été détectée.\n- Continuez votre routine d'entretien des plantes.\n- Vous pouvez réanalyser si vous remarquez des changements.",
  noDiseaseGuidanceGeneralSymptoms: "Un diagnostic spécifique n'a pas pu être établi car les symptômes sont généraux ou trop précoces.\n- Observez votre plante pendant quelques jours de plus. Réanalysez avec une nouvelle photo si les symptômes deviennent plus distincts ou s'aggravent.\n- Si les préoccupations persistent, consultez une pépinière locale ou un expert agricole.",
  noDiseaseGuidanceObservationPrompt: "Continuez à observer. Si les symptômes changent ou s'aggravent, réanalysez avec une nouvelle photo ou consultez un expert.",
  differentialDiagnosesLabel: "Diagnostics Différentiels",
  imageQualityNotesLabel: "Notes sur la Qualité de l'Image",
  qualitativeConfidenceLabel: "Confiance du Diagnostic",
  dataSourceDisclaimer: "L'analyse est basée sur des modèles de données accessibles au public. Les tests locaux sont la référence absolue pour la précision.",
  errorNetwork: "Impossible de se connecter. Veuillez vérifier votre connexion internet et réessayer.",
  errorJsonParse: "Un problème est survenu lors du traitement de la réponse de l'IA. Veuillez réessayer.",
  errorRateLimit: "Trop de requêtes. Veuillez patienter un moment et réessayer.",
  errorAnalysisGeneric: "Une erreur inattendue s'est produite lors de l'analyse. Veuillez réessayer.",
  errorAnalysisTimeout: "L'analyse prend plus de temps que prévu. Veuillez vérifier votre connexion réseau ou réessayer plus tard.",
  startDiagnosisButton: "Démarrer le Diagnostic de la Plante",
  thinkingTextAfterImageUpload: "Super, je regarde votre photo. Maintenant, vérifions l'environnement local pour un diagnostic plus précis...",
  viewMoreDetailsButton: "Voir Plus de Détails",
  hideMoreDetailsButton: "Masquer les Détails",
  summaryTab: "Résumé",
  solutionsTab: "Solutions",
  technicalDetailsTab: "Détails Techniques",
  confidenceLevelLabel: "Niveau de Confiance",
  confidenceHigh: "Élevée",
  confidenceMedium: "Modérée",
  confidenceLow: "Faible",
  confidenceUnknown: "Inconnue",
  weatherSummaryTitle: "Résumé Météo",
  environmentalSummaryTitle: "Résumé Environnemental",
  currentMonthTempTrend: "Tendance Temp. de Ce Mois",
  backendDashboardTitle: "Gestion des Services Backend",
  serviceProviderLabel: "Fournisseur(s)",
  apiKeyManagementLabel: "Gestion des Clés API",
  statusLabel: "Statut",
  aiServiceTitle: "Service d'Analyse IA (Google Gemini)",
  geminiModelInfo: "Modèle : gemini-2.5-flash-preview-04-17",
  geminiKeyInfo: "Géré de manière sécurisée par le proxy backend via le fichier .env.",
  ipLocationServiceTitle: "Service de Localisation IP",
  ipLocationProvidersInfo: "Fournisseurs : ipapi.co (Principal), ip-api.com (Secours) - via Proxy",
  ipLocationKeyInfo: "Utilise des API publiques. Gestion des clés via proxy si requis par de futurs fournisseurs.",
  weatherServiceTitle: "Service Météo",
  weatherProviderInfo: "Fournisseur : Open-Meteo - via Proxy",
  weatherKeyInfo: "Utilise des API publiques. Gestion des clés via proxy si requis par de futurs fournisseurs.",
  elevationServiceTitle: "Service d'Élévation",
  elevationProvidersInfo: "Fournisseurs : Open-Elevation (Principal), OpenTopoData (Secours) - via Proxy",
  elevationKeyInfo: "Utilise des API publiques. Gestion des clés via proxy si requis par de futurs fournisseurs.",
  soilServiceTitle: "Service de Données du Sol",
  soilProviderInfo: "Fournisseur : SoilGrids - via Proxy",
  soilKeyInfo: "Utilise des API publiques. Gestion des clés via proxy si requis par de futurs fournisseurs.",
  howToUpdateConfigText: "Note : Pour changer les fournisseurs de services ou les configurations backend, veuillez mettre à jour le fichier `server.js` du proxy backend ou les variables d'environnement selon les besoins, et redémarrez le serveur proxy. Ce tableau de bord est à titre informatif.",
  switchToDiagnosisViewButton: "Retour au Diagnostic",
  switchToDashboardViewButton: "Services Backend",
  leaveDiagnosisConfirmationTitle: "Quitter le Diagnostic ?",
  leaveDiagnosisConfirmationMessage: "Un diagnostic est en cours. Êtes-vous sûr de vouloir quitter ? Votre image et vos données actuelles seront effacées.",
  confirmButtonLabel: "Confirmer",
  cancelButtonLabel: "Annuler",

  // Newly added for centralization
  yourLocation: "Votre Localisation",
  localEnvironmentInsightsTitle: "Aperçu de l'Environnement Local",
  typeYourAnswerPlaceholder: "Tapez votre réponse ici...",
  noSpecificSolutionsFoundTitle: "Aucune Solution Spécifique Trouvée",
  noSpecificSolutionsFoundMessage: "Il n'y a pas de recommandations de solutions directes pour ce diagnostic. Continuez avec les soins généraux des plantes et l'observation, ou réessayez avec une image différente.",
  weatherDataUnavailableNoLocation: "Les données météorologiques ne peuvent pas être récupérées sans informations de localisation.",
  currentWeatherInfoUnavailable: "Les informations météorologiques actuelles n'ont pas pu être récupérées.",
  envDataUnavailableNoLocation: "Les données environnementales ne peuvent pas être récupérées sans informations de localisation.",
  ...PIPELINE_UI_STRINGS_INTERNAL[LanguageCode.FR],
};

export const ALL_UI_STRINGS: AllUiStrings = {
  [LanguageCode.TR]: UI_STRINGS_TR,
  [LanguageCode.EN]: UI_STRINGS_EN,
  [LanguageCode.DE]: UI_STRINGS_DE_FULL,
  [LanguageCode.ES]: UI_STRINGS_ES,
  [LanguageCode.PT]: UI_STRINGS_PT,
  [LanguageCode.FR]: UI_STRINGS_FR,
};


export const getWmoDescription = (code: number | undefined, uiStrings: UiStrings): string => {
  if (code === undefined || uiStrings.wmoWeatherCodes[code] === undefined) {
    return 'N/A';
  }
  return uiStrings.wmoWeatherCodes[code];
};


// --- Caching Logic for Translations (moved from LocalizationContext) ---
const translationCache = {
  get: (langCode: LanguageCode): UiStrings | null => {
    const key = `${TRANSLATION_CACHE_PREFIX}${langCode}`;
    try {
      const item = localStorage.getItem(key);
      if (!item) return null;
      const { timestamp, data } = JSON.parse(item);
      if (Date.now() - timestamp > TRANSLATION_CACHE_EXPIRY_MS) {
        localStorage.removeItem(key);
        return null;
      }
      return data;
    } catch (error) {
      console.warn(`Error reading translation from cache for ${langCode}:`, error);
      localStorage.removeItem(key);
      return null;
    }
  },
  set: throttle((langCode: LanguageCode, data: UiStrings) => {
    const key = `${TRANSLATION_CACHE_PREFIX}${langCode}`;
    try {
      const item = { timestamp: Date.now(), data };
      localStorage.setItem(key, JSON.stringify(item));
    } catch (error) {
      console.warn(`Error setting translation in cache for ${langCode}:`, error);
    }
  }, CACHE_THROTTLE_DELAY_MS)
};


// --- Helper to get strings, with fallback and caching ---
export const getEffectiveUiStrings = (langCode: LanguageCode): UiStrings => {
  const cachedStrings = translationCache.get(langCode);
  if (cachedStrings) return cachedStrings;

  const strings = ALL_UI_STRINGS[langCode] || ALL_UI_STRINGS[LanguageCode.EN]; // Fallback to English
  translationCache.set(langCode, strings);
  return strings;
};
